BEGIN;

-- Strict filters for safety
DO $$
DECLARE
  v_created_by UUID := 'ee42009d-d83e-4c12-abd1-2d8fff809b18';
  v_role TEXT := 'TEACHER';
  v_lesson_type TEXT := 'Silly Topic Debate';
  v_difficulty TEXT := 'EASY';
  v_training_module_id UUID := '8addaf36-3881-49d8-ab34-444c399bf432';
BEGIN

WITH updated_data (lesson_name, topic, user_side, ai_side, content_val, ex_topic, ex_user, ex_ai, full_json) AS (
    VALUES
        ('Cats vs. Dogs', 'Cats are better pets than dogs.', 'Dogs', 'Cats', 'Cats are quiet and easy to take care of at home.
That''s fair. Why do some people think dogs make better pets?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Cats vs. Dogs", "lesson_description": "3SL1 [3SL1d] (88%) PRIMARY | 3SL4 (85%) PRIMARY | 3-5L1 (80%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Cats are better pets than dogs."}, {"content_key": "user_side", "content_value": "Dogs"}, {"content_key": "ai_side", "content_value": "Cats"}, {"content_key": "content", "content_value": "Cats are quiet and easy to take care of at home.\nThat''s fair. Why do some people think dogs make better pets?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Summer vs. Winter', 'Summer is better than winter.', 'Winter', 'Summer', 'Summer means no school and lots of time to play outside every day.
Good point. Why do some people love winter more than summer?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Summer vs. Winter", "lesson_description": "3SL1 [3SL1d] (88%) PRIMARY | 3SL4 (85%) PRIMARY | 3-5L1 (80%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Summer is better than winter."}, {"content_key": "user_side", "content_value": "Winter"}, {"content_key": "ai_side", "content_value": "Summer"}, {"content_key": "content", "content_value": "Summer means no school and lots of time to play outside every day.\nGood point. Why do some people love winter more than summer?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Pizza vs. Tacos', 'Pizza is better than tacos.', 'Tacos', 'Pizza', 'Pizza has so many toppings you can make it any way you like.
Good point. Why do tacos have their own kind of magic?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Pizza vs. Tacos", "lesson_description": "3SL1 [3SL1d] (88%) PRIMARY | 3SL4 (85%) PRIMARY | 3-5L1 (80%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Pizza is better than tacos."}, {"content_key": "user_side", "content_value": "Tacos"}, {"content_key": "ai_side", "content_value": "Pizza"}, {"content_key": "content", "content_value": "Pizza has so many toppings you can make it any way you like.\nGood point. Why do tacos have their own kind of magic?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Morning vs. Night', 'Being a morning person is better than being a night owl.', 'Night Owls', 'Morning People', 'Mornings are quiet and give you a fresh start to get things done.
Interesting! Why do some people feel more awake and creative at night?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Morning vs. Night", "lesson_description": "3SL1 [3SL1d] (88%) PRIMARY | 3SL4 (85%) PRIMARY | 3-5L1 (80%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Being a morning person is better than being a night owl."}, {"content_key": "user_side", "content_value": "Night Owls"}, {"content_key": "ai_side", "content_value": "Morning People"}, {"content_key": "content", "content_value": "Mornings are quiet and give you a fresh start to get things done.\nInteresting! Why do some people feel more awake and creative at night?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Books vs. Movies', 'Books are better than movies.', 'Movies', 'Books', 'Books let you use your imagination to picture everything yourself.
That''s true. Why do people love watching movies?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Books vs. Movies", "lesson_description": "3SL1 [3SL1d] (88%) PRIMARY | 3SL4 (85%) PRIMARY | 3-5L1 (81%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Books are better than movies."}, {"content_key": "user_side", "content_value": "Movies"}, {"content_key": "ai_side", "content_value": "Books"}, {"content_key": "content", "content_value": "Books let you use your imagination to picture everything yourself.\nThat''s true. Why do people love watching movies?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Indoor Recess vs. Outdoor Recess', 'Outdoor recess is better than indoor recess.', 'Indoor Recess', 'Outdoor Recess', 'Outdoor recess gives you fresh air and space to run around freely.
That makes sense. Why do some students prefer indoor recess?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Indoor Recess vs. Outdoor Recess", "lesson_description": "3SL1 [3SL1d] (88%) PRIMARY | 3SL4 (85%) PRIMARY | 3-5L1 (81%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Outdoor recess is better than indoor recess."}, {"content_key": "user_side", "content_value": "Indoor Recess"}, {"content_key": "ai_side", "content_value": "Outdoor Recess"}, {"content_key": "content", "content_value": "Outdoor recess gives you fresh air and space to run around freely.\nThat makes sense. Why do some students prefer indoor recess?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Homework vs. No Homework', 'Students should not have homework on weekends.', 'Weekend Homework', 'No Weekend Homework', 'Weekends are for rest, and rested students learn better on Monday.
Interesting. Why might teachers say weekend homework is still helpful?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Homework vs. No Homework", "lesson_description": "3SL1 [3SL1d] (88%) PRIMARY | 3SL4 (86%) PRIMARY | 3-5L1 (82%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Students should not have homework on weekends."}, {"content_key": "user_side", "content_value": "Weekend Homework"}, {"content_key": "ai_side", "content_value": "No Weekend Homework"}, {"content_key": "content", "content_value": "Weekends are for rest, and rested students learn better on Monday.\nInteresting. Why might teachers say weekend homework is still helpful?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Longer Lunch vs. Shorter Lunch', 'Students should get 45 minutes for lunch.', 'Shorter Lunch', '45-Minute Lunch', 'A longer lunch gives students time to eat well and talk with friends.
That''s fair. Why might a school say a shorter lunch period is better?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Longer Lunch vs. Shorter Lunch", "lesson_description": "3SL1 [3SL1d] (88%) PRIMARY | 3SL4 (86%) PRIMARY | 3-5L1 (82%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Students should get 45 minutes for lunch."}, {"content_key": "user_side", "content_value": "Shorter Lunch"}, {"content_key": "ai_side", "content_value": "45-Minute Lunch"}, {"content_key": "content", "content_value": "A longer lunch gives students time to eat well and talk with friends.\nThat''s fair. Why might a school say a shorter lunch period is better?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Gym Class vs. Art Class', 'Gym class is more important than art class.', 'Art Class', 'Gym Class', 'Gym class keeps students healthy and gives their brains a break during the day.
Good point. Why might someone say art class is just as important?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Gym Class vs. Art Class", "lesson_description": "3SL1 [3SL1d] (88%) PRIMARY | 3SL4 (86%) PRIMARY | 3-5L1 (82%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Gym class is more important than art class."}, {"content_key": "user_side", "content_value": "Art Class"}, {"content_key": "ai_side", "content_value": "Gym Class"}, {"content_key": "content", "content_value": "Gym class keeps students healthy and gives their brains a break during the day.\nGood point. Why might someone say art class is just as important?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Crunchy vs. Smooth Peanut Butter', 'Crunchy peanut butter is better than smooth.', 'Smooth Peanut Butter', 'Crunchy Peanut Butter', 'Crunchy peanut butter adds extra flavor and texture to every bite.
That''s true. Why do so many people prefer smooth peanut butter?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Crunchy vs. Smooth Peanut Butter", "lesson_description": "3SL1 [3SL1d] (88%) PRIMARY | 3SL4 (85%) PRIMARY | 3-5L1 (82%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Crunchy peanut butter is better than smooth."}, {"content_key": "user_side", "content_value": "Smooth Peanut Butter"}, {"content_key": "ai_side", "content_value": "Crunchy Peanut Butter"}, {"content_key": "content", "content_value": "Crunchy peanut butter adds extra flavor and texture to every bite.\nThat''s true. Why do so many people prefer smooth peanut butter?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Class Pet vs. No Class Pet', 'Every classroom should have a class pet.', 'No Class Pet', 'Class Pet', 'A class pet teaches students responsibility and brings the whole class together.
Interesting. Why might a teacher decide not to have a class pet?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Class Pet vs. No Class Pet", "lesson_description": "3SL1 [3SL1d] (89%) PRIMARY | 3SL4 (86%) PRIMARY | 3-5L1 (82%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Every classroom should have a class pet."}, {"content_key": "user_side", "content_value": "No Class Pet"}, {"content_key": "ai_side", "content_value": "Class Pet"}, {"content_key": "content", "content_value": "A class pet teaches students responsibility and brings the whole class together.\nInteresting. Why might a teacher decide not to have a class pet?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Stand-Up Desks vs. Regular Desks', 'Students should be allowed to stand while working.', 'Regular Desks', 'Standing Desks', 'Standing while working helps students stay focused and feel less restless.
That makes sense. Why might some students prefer sitting at a regular desk?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Stand-Up Desks vs. Regular Desks", "lesson_description": "3SL1 [3SL1d] (89%) PRIMARY | 3SL4 (86%) PRIMARY | 3-5L1 (82%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Students should be allowed to stand while working."}, {"content_key": "user_side", "content_value": "Regular Desks"}, {"content_key": "ai_side", "content_value": "Standing Desks"}, {"content_key": "content", "content_value": "Standing while working helps students stay focused and feel less restless.\nThat makes sense. Why might some students prefer sitting at a regular desk?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Technology in Class vs. No Screens', 'Tablets and computers should be used every day in school.', 'No Screens', 'Daily Technology', 'Tablets and computers give students quick access to tools and information.
Good point. Why might too much screen time in school be a problem?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Technology in Class vs. No Screens", "lesson_description": "3SL1 [3SL1d] (89%) PRIMARY | 3SL4 (86%) PRIMARY | 3-5L1 (83%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Tablets and computers should be used every day in school."}, {"content_key": "user_side", "content_value": "No Screens"}, {"content_key": "ai_side", "content_value": "Daily Technology"}, {"content_key": "content", "content_value": "Tablets and computers give students quick access to tools and information.\nGood point. Why might too much screen time in school be a problem?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('School Uniforms vs. Casual Clothes', 'Students should wear uniforms to school.', 'Casual Clothes', 'Uniforms', 'Uniforms make mornings easier and help students focus on learning instead of clothes.
That''s fair. Why do some students feel that choosing their own clothes matters?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "School Uniforms vs. Casual Clothes", "lesson_description": "3SL1 [3SL1d] (89%) PRIMARY | 3SL4 (86%) PRIMARY | 3-5L1 (83%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Students should wear uniforms to school."}, {"content_key": "user_side", "content_value": "Casual Clothes"}, {"content_key": "ai_side", "content_value": "Uniforms"}, {"content_key": "content", "content_value": "Uniforms make mornings easier and help students focus on learning instead of clothes.\nThat''s fair. Why do some students feel that choosing their own clothes matters?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Four-Day School Week vs. Five-Day', 'School should only be four days a week.', 'Five-Day School Week', 'Four-Day School Week', 'A four-day school week gives students more time to rest and recharge.
Interesting. Why might parents and teachers say five days is better?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Four-Day School Week vs. Five-Day", "lesson_description": "3SL1 [3SL1d] (89%) PRIMARY | 3SL4 (86%) PRIMARY | 3-5L1 (83%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "School should only be four days a week."}, {"content_key": "user_side", "content_value": "Five-Day School Week"}, {"content_key": "ai_side", "content_value": "Four-Day School Week"}, {"content_key": "content", "content_value": "A four-day school week gives students more time to rest and recharge.\nInteresting. Why might parents and teachers say five days is better?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Fast vs. Careful', 'It is better to finish fast than to slow down and check your work.', 'Careful Work', 'Fast Work', 'Finishing quickly leaves more time for other tasks and shows confidence.
That''s a fair point. Why might slowing down and checking your work lead to better results?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Fast vs. Careful", "lesson_description": "3SL1 [3SL1d] (89%) PRIMARY | 3SL4 (87%) PRIMARY | 3-5L1 (83%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "It is better to finish fast than to slow down and check your work."}, {"content_key": "user_side", "content_value": "Careful Work"}, {"content_key": "ai_side", "content_value": "Fast Work"}, {"content_key": "content", "content_value": "Finishing quickly leaves more time for other tasks and shows confidence.\nThat''s a fair point. Why might slowing down and checking your work lead to better results?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Leaders vs. Followers', 'Being a good follower is just as important as being a good leader.', 'Leaders', 'Good Followers', 'Good followers keep a team moving by listening carefully and doing their part.
That''s thoughtful. Why do some people believe being a leader makes a bigger difference?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Leaders vs. Followers", "lesson_description": "3SL1 [3SL1d] (89%) PRIMARY | 3SL4 (87%) PRIMARY | 3-5L1 (84%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Being a good follower is just as important as being a good leader."}, {"content_key": "user_side", "content_value": "Leaders"}, {"content_key": "ai_side", "content_value": "Good Followers"}, {"content_key": "content", "content_value": "Good followers keep a team moving by listening carefully and doing their part.\nThat''s thoughtful. Why do some people believe being a leader makes a bigger difference?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Group Work vs. Solo Work', 'Working in a group is better than working alone.', 'Solo Work', 'Group Work', 'Group work brings in different ideas and helps everyone solve problems faster.
Good point. Why do some students do their best work on their own?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Group Work vs. Solo Work", "lesson_description": "3SL1 [3SL1d] (89%) PRIMARY | 3SL4 (87%) PRIMARY | 3-5L1 (84%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Working in a group is better than working alone."}, {"content_key": "user_side", "content_value": "Solo Work"}, {"content_key": "ai_side", "content_value": "Group Work"}, {"content_key": "content", "content_value": "Group work brings in different ideas and helps everyone solve problems faster.\nGood point. Why do some students do their best work on their own?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Rules vs. No Rules', 'Too many rules make school less fun and less creative.', 'Helpful Rules', 'Fewer Rules', 'When there are too many rules, students spend more time following them than thinking freely.
Interesting. Why might someone say rules actually help protect everyone''s creativity?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Rules vs. No Rules", "lesson_description": "3SL1 [3SL1d] (90%) PRIMARY | 3SL4 (87%) PRIMARY | 3-5L1 (84%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Too many rules make school less fun and less creative."}, {"content_key": "user_side", "content_value": "Helpful Rules"}, {"content_key": "ai_side", "content_value": "Fewer Rules"}, {"content_key": "content", "content_value": "When there are too many rules, students spend more time following them than thinking freely.\nInteresting. Why might someone say rules actually help protect everyone''s creativity?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Trying New Things vs. Sticking with What You Know', 'It is better to try new things than to stick with what you are already good at.', 'Mastering One Skill', 'Trying New Things', 'Trying new things helps you grow and find skills you never knew you had.
That''s a strong point. Why might someone say mastering one skill is more valuable?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Trying New Things vs. Sticking with What You Know", "lesson_description": "3SL1 [3SL1d] (90%) PRIMARY | 3SL4 (87%) PRIMARY | 3-5L1 (84%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "It is better to try new things than to stick with what you are already good at."}, {"content_key": "user_side", "content_value": "Mastering One Skill"}, {"content_key": "ai_side", "content_value": "Trying New Things"}, {"content_key": "content", "content_value": "Trying new things helps you grow and find skills you never knew you had.\nThat''s a strong point. Why might someone say mastering one skill is more valuable?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Learning from Mistakes vs. Learning from Success', 'You learn more from your mistakes than from your successes.', 'Success', 'Mistakes', 'Mistakes show you exactly what to fix, which helps you improve in a focused way.
That makes sense. Why might someone argue that success teaches just as much?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Learning from Mistakes vs. Learning from Success", "lesson_description": "3SL1 [3SL1d] (90%) PRIMARY | 3SL4 (87%) PRIMARY | 3-5L1 (84%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "You learn more from your mistakes than from your successes."}, {"content_key": "user_side", "content_value": "Success"}, {"content_key": "ai_side", "content_value": "Mistakes"}, {"content_key": "content", "content_value": "Mistakes show you exactly what to fix, which helps you improve in a focused way.\nThat makes sense. Why might someone argue that success teaches just as much?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Asking for Help vs. Figuring It Out Yourself', 'Asking for help is always better than struggling alone.', 'Figuring It Out Yourself', 'Asking for Help', 'Asking for help saves time and often leads to a better solution faster.
Good point. Why might someone say figuring things out yourself builds a stronger skill?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Asking for Help vs. Figuring It Out Yourself", "lesson_description": "3SL1 [3SL1d] (90%) PRIMARY | 3SL4 (87%) PRIMARY | 3-5L1 (84%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Asking for help is always better than struggling alone."}, {"content_key": "user_side", "content_value": "Figuring It Out Yourself"}, {"content_key": "ai_side", "content_value": "Asking for Help"}, {"content_key": "content", "content_value": "Asking for help saves time and often leads to a better solution faster.\nGood point. Why might someone say figuring things out yourself builds a stronger skill?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Effort vs. Natural Talent', 'Hard work matters more than natural talent.', 'Natural Talent', 'Hard Work', 'Hard work can be built up over time, while talent alone does not guarantee growth.
That''s thoughtful. Why might someone say natural talent gives a person a real head start?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Effort vs. Natural Talent", "lesson_description": "3SL1 [3SL1d] (90%) PRIMARY | 3SL4 (87%) PRIMARY | 3-5L1 (84%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Hard work matters more than natural talent."}, {"content_key": "user_side", "content_value": "Natural Talent"}, {"content_key": "ai_side", "content_value": "Hard Work"}, {"content_key": "content", "content_value": "Hard work can be built up over time, while talent alone does not guarantee growth.\nThat''s thoughtful. Why might someone say natural talent gives a person a real head start?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Fairness vs. Equality', 'Being fair and giving everyone the same thing are not always the same idea.', 'Equality', 'Fairness', 'True fairness means giving people what they actually need, which is not always the same thing.
That''s a nuanced point. Why might someone argue that treating everyone exactly the same is the only truly fair approach?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Fairness vs. Equality", "lesson_description": "3SL1 [3SL1d] (90%) PRIMARY | 3SL4 (88%) PRIMARY | 3-5L1 (85%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Being fair and giving everyone the same thing are not always the same idea."}, {"content_key": "user_side", "content_value": "Equality"}, {"content_key": "ai_side", "content_value": "Fairness"}, {"content_key": "content", "content_value": "True fairness means giving people what they actually need, which is not always the same thing.\nThat''s a nuanced point. Why might someone argue that treating everyone exactly the same is the only truly fair approach?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Changing the Rules vs. Following Them', 'When a rule is unfair, you should work to change it rather than just follow it.', 'Following Rules', 'Changing Unfair Rules', 'Working to change an unfair rule shows courage and helps everyone in the long run.
That''s a strong argument. Why might someone say following the rules first is always the right move?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Changing the Rules vs. Following Them", "lesson_description": "3SL1 [3SL1d] (90%) PRIMARY | 3SL4 (88%) PRIMARY | 3-5L1 (85%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "When a rule is unfair, you should work to change it rather than just follow it."}, {"content_key": "user_side", "content_value": "Following Rules"}, {"content_key": "ai_side", "content_value": "Changing Unfair Rules"}, {"content_key": "content", "content_value": "Working to change an unfair rule shows courage and helps everyone in the long run.\nThat''s a strong argument. Why might someone say following the rules first is always the right move?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Individual vs. Team', 'What''s best for the team is more important than what''s best for any single person.', 'Individual Needs', 'Team Needs', 'When the team succeeds, everyone benefits, so the group''s needs should come first.
Interesting. Why might someone say individual needs matter just as much as the team''s?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Individual vs. Team", "lesson_description": "3SL1 [3SL1d] (90%) PRIMARY | 3SL4 (88%) PRIMARY | 3-5L1 (85%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "What''s best for the team is more important than what''s best for any single person."}, {"content_key": "user_side", "content_value": "Individual Needs"}, {"content_key": "ai_side", "content_value": "Team Needs"}, {"content_key": "content", "content_value": "When the team succeeds, everyone benefits, so the group''s needs should come first.\nInteresting. Why might someone say individual needs matter just as much as the team''s?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Knowing vs. Understanding', 'Understanding something deeply is more valuable than memorizing a lot of facts.', 'Memorizing Facts', 'Deep Understanding', 'Deep understanding lets you solve new problems, while memorized facts can be quickly forgotten.
That''s thoughtful. Why might someone say knowing many facts gives you a real advantage?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Knowing vs. Understanding", "lesson_description": "3SL1 [3SL1d] (91%) PRIMARY | 3SL4 (88%) PRIMARY | 3-5L1 (85%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "Understanding something deeply is more valuable than memorizing a lot of facts."}, {"content_key": "user_side", "content_value": "Memorizing Facts"}, {"content_key": "ai_side", "content_value": "Deep Understanding"}, {"content_key": "content", "content_value": "Deep understanding lets you solve new problems, while memorized facts can be quickly forgotten.\nThat''s thoughtful. Why might someone say knowing many facts gives you a real advantage?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Short-Term vs. Long-Term Thinking', 'It is better to make decisions that help you now than to wait for something better later.', 'Long-Term Thinking', 'Short-Term Thinking', 'Getting something good now is real and certain, while waiting for something better is never guaranteed.
That''s fair. Why might someone say planning for the future always leads to a better outcome?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Short-Term vs. Long-Term Thinking", "lesson_description": "3SL1 [3SL1d] (91%) PRIMARY | 3SL4 (88%) PRIMARY | 3-5L1 (85%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "It is better to make decisions that help you now than to wait for something better later."}, {"content_key": "user_side", "content_value": "Long-Term Thinking"}, {"content_key": "ai_side", "content_value": "Short-Term Thinking"}, {"content_key": "content", "content_value": "Getting something good now is real and certain, while waiting for something better is never guaranteed.\nThat''s fair. Why might someone say planning for the future always leads to a better outcome?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('Saying Something vs. Staying Quiet', 'It is always better to speak up than to stay silent when something is wrong.', 'Staying Quiet', 'Speaking Up', 'Speaking up when something is wrong can protect people and stop problems before they grow.
That''s a strong point. Why might staying quiet sometimes be the wiser or kinder choice?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "Saying Something vs. Staying Quiet", "lesson_description": "3SL1 [3SL1d] (91%) PRIMARY | 3SL4 (88%) PRIMARY | 3-5L1 (86%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "It is always better to speak up than to stay silent when something is wrong."}, {"content_key": "user_side", "content_value": "Staying Quiet"}, {"content_key": "ai_side", "content_value": "Speaking Up"}, {"content_key": "content", "content_value": "Speaking up when something is wrong can protect people and stop problems before they grow.\nThat''s a strong point. Why might staying quiet sometimes be the wiser or kinder choice?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB),
        ('One Strong Voice vs. Many Small Voices', 'One person speaking clearly and loudly can change things more than many people each saying a little.', 'Many Small Voices', 'One Strong Voice', 'A single clear voice is easier to understand and remember than many smaller voices all at once.
Interesting. Why might someone say that many voices speaking together create more lasting change?
What''s your final thought?', 'Ice Cream is better than Pizza', 'Ice cream is cold and sweet, and it makes people happy on hot days!', 'Pizza has cheese and toppings and can be eaten anytime, unlike ice cream.', '{"lesson_name": "One Strong Voice vs. Many Small Voices", "lesson_description": "3SL1 [3SL1d] (91%) PRIMARY | 3SL4 (88%) PRIMARY | 3-5L1 (86%) SECONDARY", "training_module_id": "8addaf36-3881-49d8-ab34-444c399bf432", "grade": 3, "section": null, "difficulty_level": "EASY", "lesson_type": "Silly Topic Debate", "contents": [{"content_key": "topic", "content_value": "One person speaking clearly and loudly can change things more than many people each saying a little."}, {"content_key": "user_side", "content_value": "Many Small Voices"}, {"content_key": "ai_side", "content_value": "One Strong Voice"}, {"content_key": "content", "content_value": "A single clear voice is easier to understand and remember than many smaller voices all at once.\nInteresting. Why might someone say that many voices speaking together create more lasting change?\nWhat''s your final thought?"}, {"content_key": "example_topic", "content_value": "Ice Cream is better than Pizza"}, {"content_key": "example_user_side", "content_value": "Ice cream is cold and sweet, and it makes people happy on hot days!"}, {"content_key": "example_ai_side", "content_value": "Pizza has cheese and toppings and can be eaten anytime, unlike ice cream."}]}'::JSONB)
),

target_lessons AS (
    SELECT lesson_id, lesson_name, full_json
    FROM bantrly.lesson l
    JOIN updated_data ud ON l.lesson_name = ud.lesson_name
    WHERE training_module_id = v_training_module_id
      AND lesson_type = v_lesson_type
      AND difficulty_level = v_difficulty
      AND created_by = v_created_by
      AND created_by_role = v_role
),

-- 1. Update lesson_content keys
update_content AS (
  UPDATE bantrly.lesson_content lc
  SET content_value = CASE 
    WHEN content_key = 'topic' THEN ud.topic
    WHEN content_key = 'user_side' THEN ud.user_side
    WHEN content_key = 'ai_side' THEN ud.ai_side
    WHEN content_key = 'content' THEN ud.content_val
    WHEN content_key = 'example_topic' THEN ud.ex_topic
    WHEN content_key = 'example_user_side' THEN ud.ex_user
    WHEN content_key = 'example_ai_side' THEN ud.ex_ai
  END,
  updated_at = NOW()
  FROM target_lessons tl
  JOIN updated_data ud ON tl.lesson_name = ud.lesson_name
  WHERE lc.lesson_id = tl.lesson_id
    AND lc.content_key IN ('topic', 'user_side', 'ai_side', 'content', 'example_topic', 'example_user_side', 'example_ai_side')
  RETURNING lc.lesson_id
),

-- 2. Update lesson_version_new JSON
update_version AS (
  UPDATE bantrly.lesson_version_new lvn
  SET content = tl.full_json,
      created_at = NOW()
  FROM target_lessons tl
  WHERE lvn.lesson_id = tl.lesson_id
    AND lvn.is_latest = true
  RETURNING lvn.lesson_id
)

SELECT 
  (SELECT COUNT(*) FROM target_lessons) AS lessons_found,
  (SELECT COUNT(*) FROM update_content) AS content_rows_updated,
  (SELECT COUNT(*) FROM update_version) AS versions_updated;

END $$;

COMMIT;
