"""
generate_sql.py
────────────────────────────────────────────────────────────────
Reads lesson_template.xlsx and generates SQL files for any or all
of the 8 modules.

Usage:
    python generate_sql.py              # generates ALL 8 modules
    python generate_sql.py 1 3 5        # generates modules 1, 3 and 5 only
    python generate_sql.py --list       # show module names and exit

Output files:  module_1_output.sql … module_8_output.sql
"""

import sys
import json
import re
import uuid
from pathlib import Path

try:
    import openpyxl
except ImportError:
    sys.exit("❌  openpyxl not installed. Run:  pip install openpyxl")

EXCEL_FILE = "3 time silly topic update.xlsx"

# ─── Load workbook ─────────────────────────────────────────────────────────────
def load_wb():
    p = Path(EXCEL_FILE)
    if not p.exists():
        sys.exit(f"❌  '{EXCEL_FILE}' not found. Place it in the same folder as this script.")
    return openpyxl.load_workbook(p, data_only=True)

# ─── Read Common Config ────────────────────────────────────────────────────────
def read_common(wb):
    ws = wb["⚙ Common Config"]
    cfg = {}
    for row in ws.iter_rows(min_row=3, values_only=True):
        key, val = row[0], row[1]
        if key and val is not None:
            cfg[str(key).strip()] = str(val).strip()
    return cfg

# ─── Read a module sheet ───────────────────────────────────────────────────────
def read_module_sheet(wb, sheet_name):
    ws = wb[sheet_name]
    headers = [c.value for c in ws[3]]     # row 3 = column headers
    lessons = []
    for row in ws.iter_rows(min_row=5, values_only=True):  # row 4 = example, 5+ = data
        if row[0] is None or str(row[0]).strip() == "":
            continue
        record = {headers[i]: (row[i] if row[i] is not None else "") for i in range(len(headers))}
        lessons.append(record)
    return lessons

# ─── SQL helpers ───────────────────────────────────────────────────────────────
def sq(val):
    """Escape single quotes for PostgreSQL."""
    return str(val).replace("'", "''")

def new_uuid():
    return str(uuid.uuid4())

# ─── SQL template header / footer ─────────────────────────────────────────────
HEADER_TMPL = """\
-- =====================================================
-- Module {mod_num}: {mod_name} - Grade {grade} ({num_lessons} Lessons)
-- Learning Path: {learning_path_id}
-- Creator: {creator_id}
-- School: {school_id}
-- Training Module: {training_module_id}
-- Generated by generate_sql.py
-- =====================================================

DO $$
DECLARE
  v_custom_version_id UUID := '{custom_version_id}';
  v_learning_path_id UUID := '{learning_path_id}';
  v_lesson_id UUID;
BEGIN
  -- Create learning_path_version if it doesn't exist
  IF NOT EXISTS (SELECT 1 FROM bantrly.learning_path_version WHERE version_id = v_custom_version_id) THEN
    INSERT INTO bantrly.learning_path_version (
      version_id, learning_path_id, version_name, version_description,
      version_number, is_active, grade, section, created_on, created_by,
      created_by_role, is_custom, difficulty_level, school_id
    ) VALUES (
      v_custom_version_id, v_learning_path_id, '{version_name}',
      '{version_description}',
      (SELECT COALESCE(MAX(version_number), 0) + 1 FROM bantrly.learning_path_version WHERE learning_path_id = v_learning_path_id),
      true, {grade}, NULL, NOW(), '{creator_id}',
      '{creator_role}', true, '{difficulty_level}', '{school_id}'
    );
  END IF;
"""

FOOTER = "\nEND;\n$$ LANGUAGE plpgsql;\n"

# ─── Per-lesson SQL builders (one per module) ──────────────────────────────────

def lesson_block(cfg, l, mod_name, lesson_type, training_module_id, content_inserts, content_json, lesson_num):
    """Shared wrapper around lesson + lesson_content + lesson_version + sequence."""
    v_id_placeholder = "v_lesson_id"
    sort_order = l.get("sort_order", "")
    image_url  = sq(l.get("lesson_image_url", ""))
    l_name     = sq(l.get("lesson_name", f"Lesson {lesson_num}"))
    l_desc     = sq(l.get("lesson_description", ""))

    contents_json_str = json.dumps(content_json, ensure_ascii=False).replace("'", "''")

    version_content = {
        "lesson_name": l.get("lesson_name", ""),
        "lesson_description": l.get("lesson_description", ""),
        "training_module_id": training_module_id,
        "grade": int(cfg["grade"]),
        "section": None,
        "difficulty_level": cfg["difficulty_level"],
        "lesson_type": lesson_type,
        "contents": content_json,
    }
    version_json = json.dumps(version_content, ensure_ascii=False).replace("'", "''")

    return f"""
  -- Lesson {lesson_num}: {l.get("lesson_name", "")}
  v_lesson_id := gen_random_uuid();

  INSERT INTO bantrly.lesson (
    lesson_id, lesson_name, lesson_description, training_module_id,
    difficulty_level, lesson_type, created_on, created_by,
    created_by_role, is_deleted, is_assessment, grade, section, lesson_image_url
  ) VALUES (
    v_lesson_id, '{l_name}', '{l_desc}', '{training_module_id}',
    '{cfg["difficulty_level"]}',
    '{lesson_type}', NOW(), '{cfg["creator_id"]}',
    '{cfg["creator_role"]}', false, false, {cfg["grade"]}, NULL, '{image_url}'
  );

  INSERT INTO bantrly.lesson_content (content_id, lesson_id, content_key, content_value, created_at, updated_at) VALUES
{content_inserts};

  INSERT INTO bantrly.lesson_version_new (
    lesson_version_id, lesson_id, version_number, title, content, status, is_latest, created_at
  ) VALUES (
    gen_random_uuid(), v_lesson_id, 1, '{l_name}',
    '{version_json}',
    'published', true, NOW()
  );

  INSERT INTO bantrly.program_lesson_sequence_new (
    learning_path_id, version_id, school_id, lesson_id,
    lesson_type, grade, section, difficulty_level, sort_order
  ) VALUES (
    v_learning_path_id, v_custom_version_id, '{cfg["school_id"]}', v_lesson_id,
    '{lesson_type}', {cfg["grade"]}, NULL, '{cfg["difficulty_level"]}', {sort_order}
  );
"""

def ci(lesson_id_var, key, val):
    """Single lesson_content insert row."""
    return f"    (gen_random_uuid(), {lesson_id_var}, '{sq(key)}', '{sq(str(val))}', NOW(), NOW())"

# ─────── MODULE 1: Reading a Paragraph ────────────────────────────────────────
def build_module_1(wb, cfg):
    lessons = read_module_sheet(wb, "M1 - Reading Paragraph")
    training_id = cfg["module_1_training_id"]
    blocks = []
    for i, l in enumerate(lessons, 1):
        passage = l.get("passage", "")
        example = l.get("example", "")
        content_rows = "\n,".join([
            ci("v_lesson_id", "passage", passage),
            ci("v_lesson_id", "example", example),
        ])
        content_json = [
            {"content_key": "passage", "content_value": passage},
            {"content_key": "example", "content_value": example},
        ]
        blocks.append(lesson_block(cfg, l, "Reading a Paragraph", "Paragraph Reading Test",
                                   training_id, content_rows, content_json, i))
    return _wrap(cfg, 1, "Reading a Paragraph", training_id, blocks, len(lessons))

# ─────── MODULE 2: Story Building ─────────────────────────────────────────────
def build_module_2(wb, cfg):
    lessons = read_module_sheet(wb, "M2 - Story Building")
    training_id = cfg["module_2_training_id"]
    blocks = []
    for i, l in enumerate(lessons, 1):
        eq = l.get("example_question", "")
        ec = l.get("example_content", "")
        kw = l.get("keywords", "")
        content_rows = "\n,".join([
            ci("v_lesson_id", "example_question", eq),
            ci("v_lesson_id", "example_content",  ec),
            ci("v_lesson_id", "keywords",          kw),
        ])
        content_json = [
            {"content_key": "example_question", "content_value": eq},
            {"content_key": "example_content",  "content_value": ec},
            {"content_key": "keywords",          "content_value": kw},
        ]
        blocks.append(lesson_block(cfg, l, "Story Building with Keywords", "Story Building with Keywords",
                                   training_id, content_rows, content_json, i))
    return _wrap(cfg, 2, "Story Building with Keywords", training_id, blocks, len(lessons))

# ─────── MODULE 3: Q&A Bursts ─────────────────────────────────────────────────
def build_module_3(wb, cfg):
    lessons = read_module_sheet(wb, "M3 - QA Bursts")
    training_id = cfg["module_3_training_id"]
    blocks = []
    for i, l in enumerate(lessons, 1):
        theme = l.get("theme", "")
        rq    = l.get("rapid_questions", "")
        eh    = l.get("example_heading", "")
        ec    = l.get("example_content", "")
        content_rows = "\n,".join([
            ci("v_lesson_id", "theme",           theme),
            ci("v_lesson_id", "rapid_questions", rq),
            ci("v_lesson_id", "example_heading", eh),
            ci("v_lesson_id", "example_content", ec),
        ])
        content_json = [
            {"content_key": "theme",           "content_value": theme},
            {"content_key": "rapid_questions", "content_value": rq},
            {"content_key": "example_heading", "content_value": eh},
            {"content_key": "example_content", "content_value": ec},
        ]
        blocks.append(lesson_block(cfg, l, "Q&A Bursts (Quick Thinking)", "Quick Thinking",
                                   training_id, content_rows, content_json, i))
    return _wrap(cfg, 3, "Q&A Bursts (Quick Thinking)", training_id, blocks, len(lessons))

# ─────── MODULE 4: Presentation ───────────────────────────────────────────────
def build_module_4(wb, cfg):
    lessons = read_module_sheet(wb, "M4 - Presentation")
    training_id = cfg["module_4_training_id"]
    blocks = []
    for i, l in enumerate(lessons, 1):
        to  = l.get("topic_overview", "")
        pg  = l.get("preparation_guidelines", "")
        eh  = l.get("example_heading", "")
        ec  = l.get("example_content", "")
        content_rows = "\n,".join([
            ci("v_lesson_id", "topic_overview",         to),
            ci("v_lesson_id", "preparation_guidelines", pg),
            ci("v_lesson_id", "example_heading",        eh),
            ci("v_lesson_id", "example_content",        ec),
        ])
        content_json = [
            {"content_key": "topic_overview",         "content_value": to},
            {"content_key": "preparation_guidelines", "content_value": pg},
            {"content_key": "example_heading",        "content_value": eh},
            {"content_key": "example_content",        "content_value": ec},
        ]
        blocks.append(lesson_block(cfg, l, "Informative Presentation", "Presentation Skill",
                                   training_id, content_rows, content_json, i))
    return _wrap(cfg, 4, "Informative Presentation", training_id, blocks, len(lessons))

# ─────── MODULE 5: Tongue Twisters ────────────────────────────────────────────
def build_module_5(wb, cfg):
    lessons = read_module_sheet(wb, "M5 - Tongue Twisters")
    training_id = cfg["module_5_training_id"]
    blocks = []
    for i, l in enumerate(lessons, 1):
        ex = l.get("example", "")
        tt = l.get("tongue_twister", "")
        content_rows = "\n,".join([
            ci("v_lesson_id", "example",       ex),
            ci("v_lesson_id", "tongue_twister", tt),
        ])
        content_json = [
            {"content_key": "example",        "content_value": ex},
            {"content_key": "tongue_twister", "content_value": tt},
        ]
        blocks.append(lesson_block(cfg, l, "Tongue Twisters", "Pronunciation Diction",
                                   training_id, content_rows, content_json, i))
    return _wrap(cfg, 5, "Tongue Twisters", training_id, blocks, len(lessons))

# ─────── MODULE 6: Poems ──────────────────────────────────────────────────────
def build_module_6(wb, cfg):
    lessons = read_module_sheet(wb, "M6 - Poems")
    training_id = cfg["module_6_training_id"]
    blocks = []
    for i, l in enumerate(lessons, 1):
        ex = l.get("example", "")
        at = l.get("assigned_text", "")
        content_rows = "\n,".join([
            ci("v_lesson_id", "example",       ex),
            ci("v_lesson_id", "assigned_text", at),
        ])
        content_json = [
            {"content_key": "example",        "content_value": ex},
            {"content_key": "assigned_text",  "content_value": at},
        ]
        blocks.append(lesson_block(cfg, l, "Poems (Vocal Variety)", "Vocal Variety Emotion",
                                   training_id, content_rows, content_json, i))
    return _wrap(cfg, 6, "Poems (Vocal Variety)", training_id, blocks, len(lessons))

# ─────── MODULE 7: Silly Debate ───────────────────────────────────────────────
def build_module_7(wb, cfg):
    lessons = read_module_sheet(wb, "M7 - Silly Debate")
    training_id = cfg["module_7_training_id"]
    blocks = []
    for i, l in enumerate(lessons, 1):
        topic   = l.get("topic", "")
        us      = l.get("user_side", "")
        ai_s    = l.get("ai_side", "")
        content = l.get("content", "")
        et      = l.get("example_topic", "")
        eus     = l.get("example_user_side", "")
        eas     = l.get("example_ai_side", "")
        content_rows = "\n,".join([
            ci("v_lesson_id", "topic",            topic),
            ci("v_lesson_id", "user_side",         us),
            ci("v_lesson_id", "ai_side",           ai_s),
            ci("v_lesson_id", "content",           content),
            ci("v_lesson_id", "example_topic",     et),
            ci("v_lesson_id", "example_user_side", eus),
            ci("v_lesson_id", "example_ai_side",   eas),
        ])
        content_json = [
            {"content_key": "topic",            "content_value": topic},
            {"content_key": "user_side",         "content_value": us},
            {"content_key": "ai_side",           "content_value": ai_s},
            {"content_key": "content",           "content_value": content},
            {"content_key": "example_topic",     "content_value": et},
            {"content_key": "example_user_side", "content_value": eus},
            {"content_key": "example_ai_side",   "content_value": eas},
        ]
        blocks.append(lesson_block(cfg, l, "Silly Topic Debate", "Silly Topic Debate",
                                   training_id, content_rows, content_json, i))
    return _wrap(cfg, 7, "Silly Topic Debate", training_id, blocks, len(lessons))

# ─────── MODULE 8: Audio Postcards ────────────────────────────────────────────
def build_module_8(wb, cfg):
    lessons = read_module_sheet(wb, "M8 - Audio Postcards")
    training_id = cfg["module_8_training_id"]
    blocks = []
    for i, l in enumerate(lessons, 1):
        topic   = l.get("topic", "")
        instr   = l.get("instructions", "")
        et      = l.get("example_topic", "")
        ei      = l.get("example_instruction", "")
        ec      = l.get("example_content", "")
        content_rows = "\n,".join([
            ci("v_lesson_id", "topic",              topic),
            ci("v_lesson_id", "instructions",       instr),
            ci("v_lesson_id", "example_topic",      et),
            ci("v_lesson_id", "example_instruction",ei),
            ci("v_lesson_id", "example_content",    ec),
        ])
        content_json = [
            {"content_key": "topic",               "content_value": topic},
            {"content_key": "instructions",        "content_value": instr},
            {"content_key": "example_topic",       "content_value": et},
            {"content_key": "example_instruction", "content_value": ei},
            {"content_key": "example_content",     "content_value": ec},
        ]
        blocks.append(lesson_block(cfg, l, "Audio Postcards", "Personal Expression",
                                   training_id, content_rows, content_json, i))
    return _wrap(cfg, 8, "Audio Postcards", training_id, blocks, len(lessons))

# ─── Wrap header + blocks + footer ────────────────────────────────────────────
def _wrap(cfg, mod_num, mod_name, training_id, blocks, num_lessons):
    header = HEADER_TMPL.format(
        mod_num=mod_num,
        mod_name=mod_name,
        grade=cfg["grade"],
        num_lessons=num_lessons,
        learning_path_id=cfg["learning_path_id"],
        creator_id=cfg["creator_id"],
        school_id=cfg["school_id"],
        training_module_id=training_id,
        custom_version_id=cfg["custom_version_id"],
        version_name=sq(cfg["version_name"]),
        version_description=sq(cfg["version_description"]),
        creator_role=cfg["creator_role"],
        difficulty_level=cfg["difficulty_level"],
    )
    return header + "".join(blocks) + FOOTER

# ─── Module registry ──────────────────────────────────────────────────────────
MODULES = {
    1: ("Reading a Paragraph",        build_module_1),
    2: ("Story Building with Keywords", build_module_2),
    3: ("Q&A Bursts (Quick Thinking)", build_module_3),
    4: ("Informative Presentation",   build_module_4),
    5: ("Tongue Twisters",            build_module_5),
    6: ("Poems (Vocal Variety)",      build_module_6),
    7: ("Silly Topic Debate",         build_module_7),
    8: ("Audio Postcards",            build_module_8),
}

# ─── Main ─────────────────────────────────────────────────────────────────────
def main():
    args = sys.argv[1:]

    if "--list" in args:
        for num, (name, _) in MODULES.items():
            print(f"  Module {num}: {name}")
        return

    # Determine which modules to generate
    if args:
        try:
            selected = [int(a) for a in args]
        except ValueError:
            sys.exit("❌  Pass module numbers (1–8) or --list")
        for n in selected:
            if n not in MODULES:
                sys.exit(f"❌  Module {n} does not exist. Valid: 1–8")
    else:
        selected = list(MODULES.keys())

    wb  = load_wb()
    cfg = read_common(wb)

    for mod_num in selected:
        name, builder = MODULES[mod_num]
        print(f"⏳  Generating Module {mod_num}: {name} …")
        try:
            sql = builder(wb, cfg)
        except Exception as e:
            print(f"  ❌  Error: {e}")
            continue
        out_path = Path(f"module_{mod_num}_output.sql")
        out_path.write_text(sql, encoding="utf-8")
        print(f"  ✅  Saved → {out_path}  ({len(sql):,} chars)")

    print("\nDone.")

if __name__ == "__main__":
    main()
