-- Generated by update_lesson_desc.py
-- Filters: difficulty=EASY | created_by=ee42009d-d83e-4c12-abd1-2d8fff809b18 | role=TEACHER
-- Updates bantrly.lesson (lesson_description column) and
--         bantrly.lesson_version_new (lesson_description JSON key)

BEGIN;

WITH
-- M1 - Reading Paragraph: lesson_description (30 lesson(s))
m1_desc_data AS (
    SELECT * FROM (VALUES
        ('A New Seat', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R1, 3R9'),
        ('The Missing Pencil', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R1, 3R9'),
        ('Too Loud', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R1, 3R9'),
        ('Sharing the Crayons', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R1, 3R9'),
        ('A Rainy Day', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R1, 3R9'),
        ('First Day Jitters', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R1, 3R9'),
        ('The Fair Turn', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3SL1, 3R9'),
        ('Speaking Up', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3SL1, 3R9'),
        ('When Friends Disagree', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3SL1, 3R9'),
        ('The Group Project', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3SL1, 3R9'),
        ('Left Out at Lunch', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3SL1, 3R9'),
        ('Keeping a Promise', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3SL1, 3R9'),
        ('The Too-Fast Game', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3SL1, 3R9'),
        ('Different Ways to Learn', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3SL1, 3R9'),
        ('A Mistake in Class', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3SL1, 3R9'),
        ('Making Things Right', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3SL1, 3R2'),
        ('The New Student', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3SL1, 3R2'),
        ('When It''s Hard to Focus', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3SL1, 3R2'),
        ('Two Friends, One Ball', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3SL1, 3R2'),
        ('The Big Test Worry', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3SL1, 3R2'),
        ('Noticing When Someone Is Sad', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3SL1, 3R2'),
        ('Changing the Plan', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3SL1, 3R2'),
        ('Standing Up for a Friend', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3SL1, 3R2'),
        ('A Pattern I Noticed in Myself', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3R2, 3SL1'),
        ('Saying No Kindly', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3R2, 3SL1'),
        ('When the Rules Don''t Seem Fair', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3R2, 3SL1'),
        ('Taking Care of Someone Else''s Feelings', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3R2, 3SL1'),
        ('A Long Wait', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3R2, 3SL1'),
        ('Changing How I Think About Mistakes', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3R2, 3SL1'),
        ('The Group Decides Together', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3R2, 3SL1')
    ) AS v(lesson_name, new_desc)
),
m1_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m1_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'EASY'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m1_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m1_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M2 - Story Building: lesson_description (30 lesson(s))
m2_desc_data AS (
    SELECT * FROM (VALUES
        ('The Garden Helper', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R1, 3R3'),
        ('A Trip to the Library', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R1, 3R3'),
        ('Learning to Ride', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R1, 3R3'),
        ('The Baking Day', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R1, 3R3'),
        ('A Sunny Walk', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R1, 3R3'),
        ('The Classroom Pet', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R1, 3R3'),
        ('Storm at Sea', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R1, 3L1'),
        ('The Ant Colony', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R1, 3L1'),
        ('A New Pet Fish', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R1, 3L1'),
        ('Desert Animals', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R1, 3L1'),
        ('Mail Carriers', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R1, 3L1'),
        ('The Frozen Pond', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R1, 3L1'),
        ('A Busy Market', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R1, 3L1'),
        ('The Old Oak Tree', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R1, 3L1'),
        ('The Rainy Season', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R1, 3L1'),
        ('Bees and Flowers', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R9, 3L1'),
        ('Mountain Hikers', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R9, 3L1'),
        ('The Robot Helper', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R9, 3L1'),
        ('A Long Migration', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R9, 3L1'),
        ('The School Play', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R9, 3L1'),
        ('Wind Energy', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R9, 3L1'),
        ('Ocean Explorers', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R9, 3L1'),
        ('A Fire Station Visit', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R9, 3L1'),
        ('The Democracy Vote', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R9, 3R3, 3R2'),
        ('Saving Water', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R9, 3R3, 3R2'),
        ('The Inventor''s Workshop', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R9, 3R3, 3R2'),
        ('Wild Horses', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R9, 3R3, 3R2'),
        ('Bridges and Engineers', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R9, 3R3, 3R2'),
        ('A Comet Passes By', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R9, 3R3, 3R2'),
        ('The Rainforest Layers', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R9, 3R3, 3R2')
    ) AS v(lesson_name, new_desc)
),
m2_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m2_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'EASY'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m2_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m2_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M3 - QA Bursts: lesson_description (30 lesson(s))
m3_desc_data AS (
    SELECT * FROM (VALUES
        ('Morning Routine', 'Rapid Fire - NY Standards Alignment: 3SL1, 3L1, 3SL6'),
        ('School Day Basics', 'Rapid Fire - NY Standards Alignment: 3SL1, 3L1, 3SL6'),
        ('Recess Fun', 'Rapid Fire - NY Standards Alignment: 3SL1, 3L1, 3SL6'),
        ('Favorite Foods', 'Rapid Fire - NY Standards Alignment: 3SL1, 3L1, 3SL6'),
        ('Weekend Activities', 'Rapid Fire - NY Standards Alignment: 3SL1, 3L1, 3SL6'),
        ('My Family', 'Rapid Fire - NY Standards Alignment: 3SL1, 3L1, 3SL6'),
        ('Being a Good Friend', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3L1, 3SL6'),
        ('Feelings Check-In', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3L1, 3SL6'),
        ('Learning Something New', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3L1, 3SL6'),
        ('When I Need Help', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3L1, 3SL6'),
        ('My Community', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3L1, 3SL6'),
        ('Favorite Animals', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3L1, 3SL6'),
        ('Book Talk', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3L1, 3SL6'),
        ('Problem-Solving', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3L1, 3SL6'),
        ('Kindness in Action', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3L1, 3SL6'),
        ('Why Rules Matter', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3L1, 3R3'),
        ('Being Responsible', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3L1, 3R3'),
        ('Different Kinds of Smart', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3L1, 3R3'),
        ('Taking Care of Our Earth', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3L1, 3R3'),
        ('Teamwork Stories', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3L1, 3R3'),
        ('Standing Up for What''s Right', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3L1, 3R3'),
        ('Habits That Help Me Learn', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3L1, 3R3'),
        ('What Leaders Do', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3L1, 3R3'),
        ('Making Hard Choices', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3R3, 3L1'),
        ('How My Actions Affect Others', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3R3, 3L1'),
        ('Learning from Mistakes', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3R3, 3L1'),
        ('What It Means to Be Fair', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3R3, 3L1'),
        ('What I Want to Be', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3R3, 3L1'),
        ('Noticing Change Over Time', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3R3, 3L1'),
        ('My Strengths and Challenges', 'Rapid Fire - NY Standards Alignment: 3SL1, 3R9, 3R3, 3L1')
    ) AS v(lesson_name, new_desc)
),
m3_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m3_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'EASY'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m3_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m3_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M4 - Presentation: lesson_description (30 lesson(s))
m4_desc_data AS (
    SELECT * FROM (VALUES
        ('My Favorite Animal', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3L6, 3L1'),
        ('What I Did This Weekend', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3L6, 3L1'),
        ('Why We Need Rules in Games', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3L6, 3L1'),
        ('My Favorite Season', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3L6, 3L1'),
        ('How to Be a Good Listener', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3L6, 3L1'),
        ('Something I Am Good At', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3L6, 3L1'),
        ('How Recycling Helps the Planet', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3L6, 3L1'),
        ('Why Sleep Is Important', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3L6, 3L1'),
        ('How to Stay Safe Online', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3L6, 3L1'),
        ('Why Exercise Matters', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3L6, 3L1'),
        ('How to Handle a Disagreement', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3L6, 3L1'),
        ('Why Reading Every Day Helps', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3L6, 3L1'),
        ('How Weather Affects Our Day', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3L6, 3L1'),
        ('What Makes a Good Team', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3L6, 3L1'),
        ('How Plants Make Food', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3L6, 3L1'),
        ('How the Water Cycle Works', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('Why Bees Are Important', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('How the Human Heart Works', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('What Causes Seasons to Change', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('How Gravity Works', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('Why Endangered Animals Need Protection', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('How Sound Travels', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('What Makes a Community Strong', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('How the Brain Learns New Things', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L3'),
        ('Why the Ocean Matters to All of Us', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L3'),
        ('How Voting Shapes a Community', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L3'),
        ('What Scientists Do When They Are Wrong', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L3'),
        ('How Technology Changes the Way We Communicate', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L3'),
        ('Why Biodiversity Matters', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L3'),
        ('How Our Choices Affect Others', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L3')
    ) AS v(lesson_name, new_desc)
),
m4_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m4_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'EASY'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m4_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m4_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M5 - Tongue Twisters: lesson_description (30 lesson(s))
m5_desc_data AS (
    SELECT * FROM (VALUES
        ('Bright Bees Buzz', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Tiny Turtles Turn', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Silly Seals Slide', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Lovely Lions Lie', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Fluffy Frogs Flip', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Dandy Ducks Dive', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Giggling Geese Gather', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Clever Cats Climb', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Merry Mice Move', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Peaceful Puppies Play', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Seven Snug Squirrels', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Brave Bluebirds Bounce', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Friendly Frogs Flip', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Tall Tulips Twist', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Lucky Lanterns Light', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Crispy Crackers Crunch', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Shrieking Shrimp Shuffle', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Slippery Snakes Slither', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Glowing Glowworms Glow', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Three Thin Threads', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Sprinting Sprouts Spring', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Scrubbing Crabs Scrabble', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Twitching Twigs Twist', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Splitting Splinters Splashed', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Striking Streams Stream', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Thrashing Thrushes Threw', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Clinking Clocks Click', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Sparkling Sprats Sprang', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Gripping Grizzlies Growl', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6'),
        ('Scratchy Scrub Brushes Scrub', 'Tongue Twister - NY Standards Alignment: 3RF2, 3L2, 3SL6')
    ) AS v(lesson_name, new_desc)
),
m5_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m5_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'EASY'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m5_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m5_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M6 - Poems: lesson_description (30 lesson(s))
m6_desc_data AS (
    SELECT * FROM (VALUES
        ('Good Morning', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('My Voice', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Listen Up', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Keep on Trying', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Reading Time', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Rain and Puddles', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Brave Enough', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('The Quiet Moment', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('A Good Friend', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Classroom Voices', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Make a Mistake', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Sharing Space', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('The Stars at Night', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Helping Hands', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Words Matter', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('What Curiosity Feels Like', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Growing Up Slowly', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('The Last Try', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Inside the Story', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('What Fairness Looks Like', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Paying Attention', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Who I''m Becoming', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('The Sound of Learning', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Roots and Wings', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('The Shape of a Question', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('What Silence Teaches', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Both Things True', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('The Long Way Around', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('What We Leave Behind', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Making Meaning', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L2')
    ) AS v(lesson_name, new_desc)
),
m6_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m6_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'EASY'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m6_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m6_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M7 - Silly Debate: lesson_description (30 lesson(s))
m7_desc_data AS (
    SELECT * FROM (VALUES
        ('Cats vs. Dogs', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Summer vs. Winter', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Pizza vs. Tacos', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Morning vs. Night', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Books vs. Movies', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Indoor Recess vs. Outdoor Recess', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Homework vs. No Homework', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Longer Lunch vs. Shorter Lunch', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Gym Class vs. Art Class', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Crunchy vs. Smooth Peanut Butter', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Class Pet vs. No Class Pet', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Stand-Up Desks vs. Regular Desks', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Technology in Class vs. No Screens', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('School Uniforms vs. Casual Clothes', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Four-Day School Week vs. Five-Day', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Fast vs. Careful', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Leaders vs. Followers', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Group Work vs. Solo Work', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Rules vs. No Rules', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Trying New Things vs. Sticking with What You Know', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Learning from Mistakes vs. Learning from Success', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Asking for Help vs. Figuring It Out Yourself', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Effort vs. Natural Talent', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Fairness vs. Equality', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Changing the Rules vs. Following Them', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Individual vs. Team', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Knowing vs. Understanding', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Short-Term vs. Long-Term Thinking', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('Saying Something vs. Staying Quiet', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('One Strong Voice vs. Many Small Voices', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1')
    ) AS v(lesson_name, new_desc)
),
m7_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m7_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'EASY'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m7_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m7_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M8 - Audio Postcards: lesson_description (30 lesson(s))
m8_desc_data AS (
    SELECT * FROM (VALUES
        ('A Morning Stretch', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('My Favorite Snack', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('A Sound I Like', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Outside After School', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Something That Made Me Laugh', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('My Favorite Spot at Home', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Something I Learned This Week', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('A Small Problem I Solved', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('A Place I Visited', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('A Feeling I Had Today', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('What Teamwork Looked Like Today', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Something in Nature I Noticed', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Someone I Appreciate', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('A Question I Can''t Stop Thinking About', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Something I Got Better At', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('A Change I Noticed Over Time', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('A Moment When I Felt Proud', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Something That Confused Me (and Then Clicked)', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('How I Help at Home', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('What I Notice About My Community', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('A Memory That Stuck', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('What Learning Feels Like From the Inside', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Something I Changed My Mind About', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('What I Would Tell My Younger Self', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('A Question I''m Still Sitting With', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('What I Want to Be Known For', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('How a Small Moment Taught Me Something Big', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('What I''m Still Learning About Myself', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('A Sound That Tells a Story', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2'),
        ('Something I Keep Coming Back To', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2')
    ) AS v(lesson_name, new_desc)
),
m8_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m8_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'EASY'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m8_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m8_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
)

SELECT
    (SELECT COUNT(*) FROM m1_update_lesson) AS m1_lessons_updated,
    (SELECT COUNT(*) FROM m1_update_version)   AS m1_versions_updated,
    (SELECT COUNT(*) FROM m2_update_lesson) AS m2_lessons_updated,
    (SELECT COUNT(*) FROM m2_update_version)   AS m2_versions_updated,
    (SELECT COUNT(*) FROM m3_update_lesson) AS m3_lessons_updated,
    (SELECT COUNT(*) FROM m3_update_version)   AS m3_versions_updated,
    (SELECT COUNT(*) FROM m4_update_lesson) AS m4_lessons_updated,
    (SELECT COUNT(*) FROM m4_update_version)   AS m4_versions_updated,
    (SELECT COUNT(*) FROM m5_update_lesson) AS m5_lessons_updated,
    (SELECT COUNT(*) FROM m5_update_version)   AS m5_versions_updated,
    (SELECT COUNT(*) FROM m6_update_lesson) AS m6_lessons_updated,
    (SELECT COUNT(*) FROM m6_update_version)   AS m6_versions_updated,
    (SELECT COUNT(*) FROM m7_update_lesson) AS m7_lessons_updated,
    (SELECT COUNT(*) FROM m7_update_version)   AS m7_versions_updated,
    (SELECT COUNT(*) FROM m8_update_lesson) AS m8_lessons_updated,
    (SELECT COUNT(*) FROM m8_update_version)   AS m8_versions_updated;

COMMIT;
