-- Generated by update_lesson_desc.py
-- Filters: difficulty=MEDIUM | created_by=ee42009d-d83e-4c12-abd1-2d8fff809b18 | role=TEACHER
-- Updates bantrly.lesson (lesson_description column) and
--         bantrly.lesson_version_new (lesson_description JSON key)

BEGIN;

WITH
-- M1 - Reading Paragraph: lesson_description (30 lesson(s))
m1_desc_data AS (
    SELECT * FROM (VALUES
        ('Two Feelings at Once', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R1, 3-5L1'),
        ('The Borrowed Eraser', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R1, 3-5L1'),
        ('Left Out on Purpose Feeling Left Out', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3-5L1'),
        ('The Group Vote', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3-5L1'),
        ('The Apology That Was Hard', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R1, 3-5L1'),
        ('A New Partner', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3-5L1'),
        ('Two Sides of the Story', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R6, 3R9'),
        ('The Project That Fell Apart', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3SL1 [3SL1d], 3R9'),
        ('When Helping Hurts', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R6, 3-5L1'),
        ('The Compliment That Was Hard to Receive', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R1, 3-5L1'),
        ('Saying No When It Matters', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3-5L1'),
        ('The Kid Who Was Always Loud', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R6, 3R1'),
        ('What the Argument Was Really About', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3-5L1'),
        ('Practicing in Front of the Mirror', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R1, 3SL4'),
        ('When the Teacher Got It Wrong', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3SL1 [3SL1a], 3R1'),
        ('The Friend Who Changed', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R9'),
        ('The Compliment vs. the Flattery', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R6, 3R2'),
        ('Waiting for the Right Moment', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3R2'),
        ('The Shortcut That Wasn''t', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R1, 3R2'),
        ('When Two Friends Need You at the Same Time', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3-5L1'),
        ('The Unspoken Rule', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3R6'),
        ('The Trophy That Didn''t Feel Right', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6'),
        ('Carrying Someone Else''s Secret', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3R2'),
        ('The Good Reason That Still Hurt', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R9'),
        ('A Pattern She Hadn''t Seen', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R1'),
        ('Why He Never Raised His Hand', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3SL1 [3SL1b]'),
        ('The Same Word, Different Meanings', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3SL1 [3SL1d], 3-5L3'),
        ('Being Good at Something You Hate', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6'),
        ('What Changes When You Watch Yourself', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3SL4'),
        ('The Group She Would Have Missed', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6, 3R9')
    ) AS v(lesson_name, new_desc)
),
m1_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m1_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'MEDIUM'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m1_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m1_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M2 - Story Building: lesson_description (30 lesson(s))
m2_desc_data AS (
    SELECT * FROM (VALUES
        ('The Weather Forecast', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3-5L1'),
        ('A Map of Our Neighborhood', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R7, 3R1'),
        ('How Animals Stay Safe', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R3'),
        ('Reducing Waste at School', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R3'),
        ('How Seeds Travel', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R2'),
        ('Making Choices with Money', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R2'),
        ('The Food Web', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R7, 3L4'),
        ('Push, Pull, and Gravity', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R7, 3R2, 3L4'),
        ('The Water Cycle', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R7, 3L4'),
        ('How Communities Make Decisions', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R8, 3-5L1'),
        ('Animal Migration', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R7, 3L4'),
        ('Rocks and How They Form', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R7, 3R2, 3L4'),
        ('Reading for Clues', 'Build a Story with Keywords - NY Standards Alignment: 3R1, 3R3, 3L4, 3-5L1'),
        ('Different Kinds of Energy', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R7, 3L4'),
        ('The Life Cycle of a Butterfly', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R3, 3L4'),
        ('Cause and Effect', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R1, 3-5L1'),
        ('Point of View in Stories', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R6, 3R9, 3R2'),
        ('Ancient Artifacts', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R7, 3R2, 3R3'),
        ('How Laws Protect People', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R8, 3-5L1'),
        ('Plant and Animal Partnerships', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R9, 3L4'),
        ('How Inventors Solve Problems', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R2, 3R9'),
        ('Traditions Across Cultures', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R9, 3R2, 3R6'),
        ('Choices and Their Consequences', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R8, 3R9'),
        ('What Makes Something Fair', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R8, 3R6'),
        ('Trade and Barter', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R9, 3R3'),
        ('How Stories Get Passed Down', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R9, 3R2, 3R6'),
        ('Taking Care of the Environment', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R3, 3R9'),
        ('Cooperation Makes Things Possible', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R3, 3R9'),
        ('How Maps Show Power', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R6, 3R7, 3R2'),
        ('Symbols and What They Mean', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R9, 3L5')
    ) AS v(lesson_name, new_desc)
),
m2_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m2_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'MEDIUM'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m2_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m2_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M3 - QA Bursts: lesson_description (30 lesson(s))
m3_desc_data AS (
    SELECT * FROM (VALUES
        ('A Book I Really Got Into', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3-5L1'),
        ('When I Had to Wait for Something', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3-5L1'),
        ('A Time I Helped Someone', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R9, 3-5L1'),
        ('Working in a Group', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1b], 3SL1 [3SL1c], 3-5L1'),
        ('Something I Made', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3-5L1'),
        ('My Favorite Place Outside', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('A Time I Had to Be Brave', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3SL6, 3-5L1'),
        ('When Things Didn''t Go as Planned', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3SL6, 3-5L1'),
        ('My Favorite Story Character', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3R6, 3-5L1'),
        ('How Animals Survive Winter', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1c], 3R2, 3SL6, 3-5L1'),
        ('Something I Changed My Mind About', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R6, 3SL3, 3-5L1'),
        ('Describing a Place I Love', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3L3, 3-5L1'),
        ('Choosing the Right Words', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3SL6, 3L3, 3-5L1'),
        ('A Rule That Actually Makes Sense', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1c], 3R8, 3SL6, 3-5L1'),
        ('A Problem My Class Solved Together', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1b], 3SL1 [3SL1c], 3R9, 3-5L1'),
        ('What I Notice About the Seasons', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R2, 3SL4, 3-5L1'),
        ('A Mistake I Made and Fixed', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3SL3, 3-5L1'),
        ('Learning from an Older Person', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R9, 3SL3, 3-5L1'),
        ('Comparing Two Animals', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1c], 3R9, 3R2, 3-5L1'),
        ('A Time I Made a Hard Choice', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3R2, 3-5L1'),
        ('Something That Surprised Me in Nature', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R2, 3SL6, 3-5L1'),
        ('How I Help at Home', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3R9, 3-5L1'),
        ('When Someone Taught Me Something', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3SL3, 3-5L1'),
        ('Being Responsible at School and Home', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R2, 3R3, 3-5L1'),
        ('What Makes a Good Leader', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3R6, 3-5L1'),
        ('Different Ways People Learn', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R2, 3SL3, 3-5L1'),
        ('What My Community Looks Like', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1c], 3R9, 3R2, 3-5L1'),
        ('How I Know When I Understand Something', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R2, 3SL3, 3-5L1'),
        ('What Kind of Person I Want to Be', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3R6, 3-5L1'),
        ('Fairness vs. Sameness', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R9, 3R8, 3-5L1')
    ) AS v(lesson_name, new_desc)
),
m3_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m3_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'MEDIUM'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m3_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m3_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M4 - Presentation: lesson_description (30 lesson(s))
m4_desc_data AS (
    SELECT * FROM (VALUES
        ('Why We Have Rules at School', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3-5L1, 3-5L3'),
        ('How Your Brain Learns', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3-5L1'),
        ('What Makes a Good Apology', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3-5L1, 3-5L3'),
        ('How Tides Work', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3-5L1'),
        ('Why Sleep Matters More Than You Think', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3-5L1'),
        ('How Birds Find Their Way', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7'),
        ('How Recycling Really Works', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7'),
        ('What the Water Cycle Does for Us', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7'),
        ('How Volcanoes Create New Land', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3-5L1'),
        ('The Science of Camouflage', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7'),
        ('How the Printing Press Changed Reading', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7'),
        ('Why Maps Are Never Perfectly Accurate', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7'),
        ('How the Immune System Fights Infection', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7'),
        ('What Soil Is Actually Made Of', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7'),
        ('Why Bridges Are Shaped the Way They Are', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7'),
        ('How Memory Actually Works', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7'),
        ('How Language Shapes Thought', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3-5L3'),
        ('The Physics of Sound', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7'),
        ('Why Stories Are More Persuasive Than Facts', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7'),
        ('What Makes Evidence Strong', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8'),
        ('How Small Actions Build Habits', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7'),
        ('The Logic of Classification', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7'),
        ('Why Ecosystems Need Balance', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7'),
        ('How Scientists Change Their Minds', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8'),
        ('The Ethics of Keeping Secrets', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3-5L3'),
        ('Why Disagreement Is Useful', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8'),
        ('How Perspective Changes What We See', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8'),
        ('The Power of Asking Better Questions', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R6'),
        ('What Makes Information Trustworthy', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8'),
        ('How Communities Solve Problems Together', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7')
    ) AS v(lesson_name, new_desc)
),
m4_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m4_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'MEDIUM'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m4_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m4_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M5 - Tongue Twisters: lesson_description (30 lesson(s))
m5_desc_data AS (
    SELECT * FROM (VALUES
        ('Wiggly Worms Weave Webs', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Golden Geese Glide', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Rushing Rabbits Race', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Dizzy Dolphins Dash', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Muddy Moose Munch Mushrooms', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Shiny Shells Shine', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Six Slippery Snails', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Three Thick Thorny Thistles', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Plump Purple Plums', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Crunchy Crickets Creep', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Bright Bronze Beetles', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Twisting Twigs Tangle', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Freckled Frogs Flip', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Greedy Gray Geese', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Clapping Clams Clatter', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Grumpy Groundhogs Groan', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Creaky Cranes Carry Cargo', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Slender Swallows Swoop', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Wobbly Wolves Wade', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Striped Starfish Stretch', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Brown Bluebirds Brush Blossoms', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Sneaky Snakes Slither', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Prancing Ponies Prance', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Scruffy Squirrels Scramble', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Stiff Straight Strands Stretch', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Thirty Thick Threads', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Flickering Fireflies Flit', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Spotted Sparrows Spring', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Glittering Glaciers Glow', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Skillful Skunks Sketch Shapes', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6')
    ) AS v(lesson_name, new_desc)
),
m5_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m5_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'MEDIUM'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m5_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m5_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M6 - Poems: lesson_description (30 lesson(s))
m6_desc_data AS (
    SELECT * FROM (VALUES
        ('The First Try', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('After the Rain', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('My Best Friend', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Morning Light', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('The Mistake', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Autumn Leaves', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Two Feelings', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('The Book I Couldn''t Close', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Practicing', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Winter Morning', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('The Hard Question', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Listening', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('The New Student', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Spring Arrives', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Reading Together', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('The Long Way Around', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('What I Keep', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Growing Slowly', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('The Storm That Passed', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('What I Notice', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('The Question Behind the Question', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Different and the Same', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('What the Tree Knows', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Roots and Wings', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Both at Once', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Silence Before Speaking', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Small and Important', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Reading the Room', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('The Echo', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('What I''m Still Learning', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3L3')
    ) AS v(lesson_name, new_desc)
),
m6_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m6_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'MEDIUM'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m6_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m6_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M7 - Silly Debate: lesson_description (30 lesson(s))
m7_desc_data AS (
    SELECT * FROM (VALUES
        ('Rainy Days vs. Sunny Days', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Libraries vs. Playgrounds', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Drawing vs. Writing', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Mountains vs. Beach', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Big Birthday Party vs. Small One', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Lunch from Home vs. School Lunch', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Reading Silently vs. Reading Aloud', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Long Projects vs. Short Assignments', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Field Trips vs. Guest Speakers', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('One Close Friend vs. a Big Group', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Made-Up Games vs. Games with Rules', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Keeping a Journal vs. Not Keeping One', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Before Lunch vs. After Lunch', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('School Garden vs. No Garden', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Mastering One Skill vs. Trying Many Things', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Hard Truth vs. Kind White Lie', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Being the Best vs. Getting Better', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Winning as a Team vs. Succeeding Alone', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Being Kind Publicly vs. Being Kind in Private', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Following Instructions vs. Finding Your Own Way', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Apologizing Right Away vs. Waiting to Calm Down', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Changing Plans vs. Sticking With Them', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Amazing at One Thing vs. Good at Many', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Sharing an Unpopular Opinion vs. Going Along', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Strict Teacher vs. Easygoing Teacher', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Quick Decision vs. Waiting for More Information', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Admitting You Don''t Know vs. Trying First', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Doing Things for Yourself vs. Doing Things for Others', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('The Leader Who Plans vs. The Leader Who Listens', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Reading for Fun vs. Reading to Learn', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1')
    ) AS v(lesson_name, new_desc)
),
m7_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m7_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'MEDIUM'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m7_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m7_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M8 - Audio Postcards: lesson_description (30 lesson(s))
m8_desc_data AS (
    SELECT * FROM (VALUES
        ('Something Beautiful in an Unexpected Place', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Something I Made From Scratch', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('My Favorite Kind of Weather', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('A Time I Had to Start Over', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('My Neighborhood at Two Different Times of Day', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('A Time I Helped Cook or Prepare a Meal', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('A School Day That Surprised Me', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Two Very Different Places I Know', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('A Conversation I Keep Thinking About', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Something That Used to Scare Me', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('How I Prepared for Something That Mattered', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('A Time I Noticed Someone Else Needed Help', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('My Classroom at Two Very Different Moments', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Something I Observed About an Animal', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('A Day That Started Badly and Turned Around', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('A Time I Disagreed With Someone and We Were Both Partly Right', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Two Things I Want That Pull in Different Directions', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('A Person Who Sees Something Differently From Me', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Something I Know That Most People My Age Don''t', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Something I Do When No One Is Watching', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('What I Notice About How I Learn Best', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('A Moment When I Noticed My Own Reaction', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('A Time I Was More Capable Than I Expected', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('What Patience Actually Felt Like', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Something I Believed That Turned Out to Be More Complicated', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('What I Would Do Differently', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('Something I''m Working on Changing About How I Respond', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('What Makes My Classroom a Good or Hard Place to Learn', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('A Time Someone Surprised Me With Unexpected Kindness', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L3'),
        ('A Time I Said the Right Thing Without Planning To', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3L2')
    ) AS v(lesson_name, new_desc)
),
m8_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m8_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'MEDIUM'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m8_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m8_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
)

SELECT
    (SELECT COUNT(*) FROM m1_update_lesson) AS m1_lessons_updated,
    (SELECT COUNT(*) FROM m1_update_version)   AS m1_versions_updated,
    (SELECT COUNT(*) FROM m2_update_lesson) AS m2_lessons_updated,
    (SELECT COUNT(*) FROM m2_update_version)   AS m2_versions_updated,
    (SELECT COUNT(*) FROM m3_update_lesson) AS m3_lessons_updated,
    (SELECT COUNT(*) FROM m3_update_version)   AS m3_versions_updated,
    (SELECT COUNT(*) FROM m4_update_lesson) AS m4_lessons_updated,
    (SELECT COUNT(*) FROM m4_update_version)   AS m4_versions_updated,
    (SELECT COUNT(*) FROM m5_update_lesson) AS m5_lessons_updated,
    (SELECT COUNT(*) FROM m5_update_version)   AS m5_versions_updated,
    (SELECT COUNT(*) FROM m6_update_lesson) AS m6_lessons_updated,
    (SELECT COUNT(*) FROM m6_update_version)   AS m6_versions_updated,
    (SELECT COUNT(*) FROM m7_update_lesson) AS m7_lessons_updated,
    (SELECT COUNT(*) FROM m7_update_version)   AS m7_versions_updated,
    (SELECT COUNT(*) FROM m8_update_lesson) AS m8_lessons_updated,
    (SELECT COUNT(*) FROM m8_update_version)   AS m8_versions_updated;

COMMIT;
