-- Generated by update_lesson_desc.py
-- Filters: difficulty=HARD | created_by=ee42009d-d83e-4c12-abd1-2d8fff809b18 | role=TEACHER
-- Updates bantrly.lesson (lesson_description column) and
--         bantrly.lesson_version_new (lesson_description JSON key)

BEGIN;

WITH
-- M1 - Reading Paragraph: lesson_description (30 lesson(s))
m1_desc_data AS (
    SELECT * FROM (VALUES
        ('The Seat She Didn''t Expect', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R1'),
        ('The Moment Before', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R1'),
        ('A Rainy Recess', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R1'),
        ('Asking', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R1'),
        ('The Thing She Didn''t Know She Could Do', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6'),
        ('Noticing', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3SL4'),
        ('The Practice That Finally Worked', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3-5L1'),
        ('What He Did Without Thinking', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6, 3-5L1'),
        ('She Changed Her Mind', 'Reading a Paragraph - NY Standards Alignment: 3R1, 3R3, 3R2, 3R6'),
        ('The Group She Hadn''t Expected', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R9, 3R6'),
        ('The Question She Asked a Stranger', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R9, 3-5L1'),
        ('The Classmate He''d Had Wrong', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R6, 3R2, 3R9'),
        ('The Afternoon in the Library', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R1, 3L3'),
        ('Finishing Alone', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6, 3-5L1'),
        ('The Moment She Felt She Belonged', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6, 3R9'),
        ('Losing Well', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6, 3R9'),
        ('What She Heard in Her Own Voice', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6, 3L3'),
        ('The Friendship That Started With a Disagreement', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R9, 3R2, 3R6'),
        ('The Thing She Made', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6, 3L3'),
        ('What Her Teacher Said', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6, 3R1'),
        ('A Day That Went Better Than He Thought', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6, 3-5L1'),
        ('When She Found the Right Words', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6, 3SL1 [3SL1d]'),
        ('Understanding Something He''d Been Missing', 'Reading a Paragraph - NY Standards Alignment: 3R6, 3R2, 3R1, 3R9'),
        ('Ready', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6, 3R9'),
        ('The Decision She Made Herself', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6, 3R9'),
        ('A New Way of Seeing the Room', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6, 3L3'),
        ('Letting Someone In', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6, 3R9'),
        ('What She Found Out She Loved', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6, 3L3'),
        ('What She Carried Home', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6, 3L3'),
        ('Saying the True Thing', 'Reading a Paragraph - NY Standards Alignment: 3R3, 3R2, 3R6, 3R1')
    ) AS v(lesson_name, new_desc)
),
m1_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m1_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'HARD'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m1_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m1_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M2 - Story Building: lesson_description (30 lesson(s))
m2_desc_data AS (
    SELECT * FROM (VALUES
        ('Standing Up for Yourself', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3-5L1'),
        ('A Theory and the Evidence', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R7, 3R2, 3L4'),
        ('The Narrator''s Choices', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R6, 3R3, 3L5'),
        ('Citizens and Community', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R8, 3-5L1'),
        ('Perseverance in Practice', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R3, 3R2, 3-5L1'),
        ('The Power of Asking Why', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R6, 3R2, 3R8'),
        ('How Light Bends', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R7, 3R2, 3L4'),
        ('How Maps Carry Perspective', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R6, 3R7, 3R2'),
        ('What Habits Do to the Brain', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R7, 3L4'),
        ('How Authors Persuade', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R8, 3R6, 3R2'),
        ('How Ecosystems Balance', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R7, 3L4'),
        ('The History in a Name', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R9, 3L5'),
        ('What Primary Sources Show', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R6, 3R7, 3R9'),
        ('How Communities Change', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R9, 3R8'),
        ('The Difference Between Knowing and Understanding', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R7, 3L4'),
        ('How Figurative Language Works', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3L5, 3R2, 3L3'),
        ('Supply, Demand, and Scarcity', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R8, 3R7'),
        ('How Perspective Shapes Understanding', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R6, 3R2, 3R9'),
        ('How Arguments Are Structured', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R8, 3R6, 3R2'),
        ('What Makes a Theme Universal', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R9, 3L5'),
        ('How Technology Connects and Separates', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R8, 3R6'),
        ('What Makes Evidence Reliable', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R8, 3R7, 3R2'),
        ('How Advocacy Drives Change', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R8, 3R9'),
        ('How Ecosystems Recover', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R7, 3L4'),
        ('Language and Identity', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R6, 3R2, 3R9'),
        ('Cause, Effect, and Complexity', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R7, 3R8'),
        ('What Democracy Requires of Citizens', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R8, 3R6'),
        ('How Individuals Shape Culture', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R9, 3R6'),
        ('How Power and Responsibility Are Connected', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R8, 3R6'),
        ('What the Stories We Tell About Ourselves Do', 'Build a Story with Keywords - NY Standards Alignment: 3L6, 3R2, 3R3, 3R6')
    ) AS v(lesson_name, new_desc)
),
m2_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m2_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'HARD'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m2_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m2_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M3 - QA Bursts: lesson_description (30 lesson(s))
m3_desc_data AS (
    SELECT * FROM (VALUES
        ('When Rules Feel Unfair', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R8, 3-5L1'),
        ('Being Counted On', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3-5L1'),
        ('What Curiosity Looks Like in Practice', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R2, 3-5L1'),
        ('The Hardest Choices', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3-5L1'),
        ('Noticing What Others Miss', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('What Being Part of a Community Requires', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1c], 3R9, 3-5L1'),
        ('Effort, Progress, and What They Don''t Guarantee', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R2, 3SL3, 3-5L1'),
        ('What Fairness Actually Requires', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R8, 3R6, 3-5L1'),
        ('Learning From Someone Different From You', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1c], 3R9, 3SL3, 3-5L1'),
        ('When Something Feels Wrong', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R8, 3R6, 3-5L1'),
        ('How Groups Make Better Decisions', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1b], 3R8, 3SL1 [3SL1c], 3-5L1'),
        ('What Makes Someone Trustworthy', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3R9, 3-5L1'),
        ('Patterns and What They Tell You', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R2, 3R3, 3-5L1'),
        ('When Helping Gets Complicated', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3R6, 3-5L1'),
        ('When Two Right Things Conflict', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R8, 3R6, 3-5L1'),
        ('Standing Up When It Costs You', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3R8, 3-5L1'),
        ('How Your Actions Affect Others', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R9, 3R8, 3-5L1'),
        ('What Character Looks Like Under Pressure', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3R6, 3-5L1'),
        ('Understanding Both Sides of a Disagreement', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R6, 3R8, 3-5L1'),
        ('When You Notice Something Others Don''t', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R9, 3R8, 3-5L1'),
        ('What Persistence Actually Is', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R2, 3R3, 3-5L1'),
        ('What Integrity Looks Like in Small Moments', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3R2, 3-5L1'),
        ('How Small Actions Build Into Patterns', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R2, 3R9, 3-5L1'),
        ('When Change Is Difficult Even When It''s Right', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R2, 3R3, 3-5L1'),
        ('What Makes Something Worth Doing Without Recognition', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3R6, 3-5L1'),
        ('How Perspective Shapes What We See', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R6, 3R9, 3-5L1'),
        ('When Honesty Is More Complicated Than Telling the Truth', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3R8, 3-5L1'),
        ('What You Owe to the Communities You Belong To', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R9, 3R8, 3-5L1'),
        ('What It Means to Actually Change', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R3, 3R2, 3-5L1'),
        ('How What You Notice Shapes What You Think', 'Rapid Fire - NY Standards Alignment: 3SL1 [3SL1d], 3R6, 3R2, 3-5L1')
    ) AS v(lesson_name, new_desc)
),
m3_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m3_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'HARD'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m3_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m3_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M4 - Presentation: lesson_description (30 lesson(s))
m4_desc_data AS (
    SELECT * FROM (VALUES
        ('How the Moon Shapes Earth''s Oceans', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('Why Maps Can Be Misleading', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('How Authors Build Characters', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L3'),
        ('What Stars Are Made Of and Why They Shine', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('What Makes a Community Resilient', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('How Animals Communicate Without Words', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('How Plate Tectonics Shapes Earth''s Surface', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('Why Equal and Fair Are Not the Same', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8, 3L3'),
        ('How Memory Works in the Brain', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('How Democracy Functions and Why It''s Fragile', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8, 3L3'),
        ('How Migration Has Shaped Nations', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('How Scientists Use Evidence to Change Their Minds', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('What Biodiversity Does for Ecosystems', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('How Authors Use Structure to Shape Meaning', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L3'),
        ('How Climate Has Changed Over Earth''s History', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('How Perspective Is Built Into Texts', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8, 3L3'),
        ('How Trade-offs Shape Every Decision', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8, 3L3'),
        ('How Civic Participation Beyond Voting Shapes Society', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8, 3L3'),
        ('How the Human Body Responds to Exercise', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('How the Same Event Can Be Remembered Differently by Different People', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('How Language Has Shaped History', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8, 3L3'),
        ('How Economic Inequality Affects Education', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R7, 3L6'),
        ('How Stories Are Used to Build and Challenge Power', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8, 3L3'),
        ('How Individuals Have Changed the Direction of History', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8, 3L3'),
        ('How Systems Produce Unintended Consequences', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8, 3L3'),
        ('How Reading Changes How We Think', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8, 3L3'),
        ('What Justice Requires — Beyond Following Rules', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8, 3L3'),
        ('How Scientific Models Are Built and Revised', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8, 3L3'),
        ('Why Freedom of Expression Has Limits — and Why Those Limits Are Hard to Draw', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8, 3L3'),
        ('How Communities Repair After Conflict', 'Short Informative Presentation - NY Standards Alignment: 3SL4, 3W2, 3R8, 3L3')
    ) AS v(lesson_name, new_desc)
),
m4_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m4_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'HARD'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m4_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m4_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M5 - Tongue Twisters: lesson_description (30 lesson(s))
m5_desc_data AS (
    SELECT * FROM (VALUES
        ('Striped Storks Stride', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Shiny Shells Shift', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Three Thrushes Thrash', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Spiral Springs Spread', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Clever Crows Clutch', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Splotchy Snails Slip', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Striped Skinks Skip', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Twisted Twigs Twirl', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Shrewd Shrews Shred', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Flipped Freckled Frogs', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Whistling Winds Whirl', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Crackling Creek Crabs', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Spotted Starlings Swoop', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Stealthy Scorpions Scuttle', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Screaming Swallows Sweep', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Stitched Scarves Strewn', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Thrilling Thresholds Thrust', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Sprightly Squirrels Sprint', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Slippery Snowflakes Spiral', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Swift Starlings Skim', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Scrunching Spring Sprockets', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Swishing Swans Swept', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Stretching Sprouts Strain', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Strangely Twisted Thornbushes', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Crinkled Crustaceans Crawled', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Sprawling Speckled Sparrows', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Shriveled Shrunken Shrubs', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Swiftly Switching Streaks', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Sprinkling Sprinklers Sprayed', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6'),
        ('Stretching Straining Storks', 'Tongue Twister - NY Standards Alignment: 3RF4a, 3-5L2, 3SL6')
    ) AS v(lesson_name, new_desc)
),
m5_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m5_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'HARD'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m5_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m5_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M6 - Poems: lesson_description (30 lesson(s))
m6_desc_data AS (
    SELECT * FROM (VALUES
        ('Listening', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL1 [3SL1d], 3-5L2'),
        ('Changing Your Mind', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL1, 3-5L2'),
        ('Asking Why', 'Recite a Poem - NY Standards Alignment: 3SL4, 3-5L2, 3SL6'),
        ('Making Mistakes', 'Recite a Poem - NY Standards Alignment: 3SL4, 3-5L2, 3SL6'),
        ('Trying Again', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL1, 3-5L2'),
        ('Patience', 'Recite a Poem - NY Standards Alignment: 3SL4, 3-5L2, 3SL6'),
        ('Noticing Others', 'Recite a Poem - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L2'),
        ('When Words Are Hard to Find', 'Recite a Poem - NY Standards Alignment: 3SL4, 3-5L1, 3-5L2'),
        ('The Space Before Speaking', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3-5L1'),
        ('Being Brave Without Knowing It', 'Recite a Poem - NY Standards Alignment: 3SL4, 3R3, 3-5L1'),
        ('Losing and Learning', 'Recite a Poem - NY Standards Alignment: 3SL4, 3-5L2, 3SL1'),
        ('What Fairness Feels Like', 'Recite a Poem - NY Standards Alignment: 3SL1 [3SL1a], 3SL4, 3-5L1'),
        ('When Quiet Is Loud', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL1, 3-5L2'),
        ('Deciding Alone', 'Recite a Poem - NY Standards Alignment: 3SL4, 3R3, 3-5L1'),
        ('The Weight of Kindness', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL1, 3-5L2'),
        ('The Shape of Courage', 'Recite a Poem - NY Standards Alignment: 3SL4, 3-5L2, 3R3'),
        ('When Something New Feels Wrong', 'Recite a Poem - NY Standards Alignment: 3SL4, 3-5L1, 3SL1'),
        ('Choosing Carefully', 'Recite a Poem - NY Standards Alignment: 3SL4, 3-5L2, 3R3'),
        ('Want Versus Need', 'Recite a Poem - NY Standards Alignment: 3SL1 [3SL1a], 3SL4, 3-5L1'),
        ('Finding Your Pace', 'Recite a Poem - NY Standards Alignment: 3SL4, 3-5L2, 3SL6'),
        ('What Persistence Looks Like', 'Recite a Poem - NY Standards Alignment: 3SL4, 3R3, 3-5L2'),
        ('When Understanding Arrives', 'Recite a Poem - NY Standards Alignment: 3SL4, 3RF4a, 3-5L2'),
        ('Growing Without Noticing', 'Recite a Poem - NY Standards Alignment: 3SL4, 3R3, 3-5L1'),
        ('What Thinking Is Made Of', 'Recite a Poem - NY Standards Alignment: 3SL4, 3-5L2, 3SL1'),
        ('The Voice You Choose', 'Recite a Poem - NY Standards Alignment: 3SL4, 3SL6, 3-5L1'),
        ('When Silence Speaks', 'Recite a Poem - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L2'),
        ('Learning as a Map', 'Recite a Poem - NY Standards Alignment: 3SL4, 3-5L2, 3R3'),
        ('What You Carry Forward', 'Recite a Poem - NY Standards Alignment: 3SL4, 3-5L1, 3SL6'),
        ('The Edge of What You Know', 'Recite a Poem - NY Standards Alignment: 3SL4, 3-5L2, 3RF4a'),
        ('Beginning Again', 'Recite a Poem - NY Standards Alignment: 3SL4, 3R3, 3-5L1')
    ) AS v(lesson_name, new_desc)
),
m6_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m6_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'HARD'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m6_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m6_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M7 - Silly Debate: lesson_description (30 lesson(s))
m7_desc_data AS (
    SELECT * FROM (VALUES
        ('Hand Notes vs. Memorizing', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Reading New vs. Rereading', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Working Alone vs. Pairs', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Asking for Help vs. Figuring It Out', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Learning from Mistakes vs. Success', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Hardest Task First vs. Easiest', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Consistency vs. Creativity', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Rules vs. Instinct', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Thinking Before Speaking vs. Speaking to Think', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Being Early vs. On Time', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Improving Weaknesses vs. Strengths', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Detailed Feedback vs. Simple Praise', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Teaching Others vs. Self-Study', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Curiosity vs. Caution', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Planning vs. Going with the Flow', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Confidence vs. Humility', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Tradition vs. Innovation', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Being Direct vs. Being Gentle', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Depth vs. Breadth', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Standing Out vs. Fitting In', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Admitting You''re Wrong vs. Explaining Your Reasoning', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Trusting Instincts vs. Trusting Evidence', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Learning from History vs. Imagining the Future', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Thinking Out Loud vs. Thinking in Silence', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Sharing Early vs. Waiting Until Perfect', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Failing Fast vs. Planning Carefully', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Effort vs. Results', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Honesty vs. Kindness', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Adapting vs. Staying Consistent', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1'),
        ('Fewer Better Questions vs. Many Questions', 'Silly Topic Discussion - NY Standards Alignment: 3SL1 [3SL1c], 3SL4, 3-5L1')
    ) AS v(lesson_name, new_desc)
),
m7_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m7_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'HARD'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m7_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m7_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
),

-- M8 - Audio Postcards: lesson_description (30 lesson(s))
m8_desc_data AS (
    SELECT * FROM (VALUES
        ('A Moment I Felt Proud of Myself', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3-5L2'),
        ('Helping Without Being Asked', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3-5L1'),
        ('A Challenge I Overcame at School', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3-5L2'),
        ('A Morning I Felt Ready to Learn', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3-5L1'),
        ('A Time I Changed My Mind', 'Audio Postcard - NY Standards Alignment: 3SL4, 3-5L1, 3SL6'),
        ('Staying Calm When Things Felt Hard', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3-5L2'),
        ('How My Team Solved a Problem', 'Audio Postcard - NY Standards Alignment: 3SL1 [3SL1a], 3SL4, 3-5L1'),
        ('When Careful Listening Made a Difference', 'Audio Postcard - NY Standards Alignment: 3SL1 [3SL1d], 3SL4, 3-5L1'),
        ('When Someone Needed Encouragement', 'Audio Postcard - NY Standards Alignment: 3SL1, 3SL4, 3-5L1'),
        ('Disagreeing Respectfully', 'Audio Postcard - NY Standards Alignment: 3SL1 [3SL1a], 3SL4, 3-5L1'),
        ('A Goal I Am Working Toward', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3-5L1'),
        ('When Waiting Was Worth It', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3-5L2'),
        ('Something That Surprised Me in a Lesson', 'Audio Postcard - NY Standards Alignment: 3SL4, 3-5L1, 3SL6'),
        ('Noticing Kindness Around Me', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3-5L1'),
        ('When Practice Started to Work', 'Audio Postcard - NY Standards Alignment: 3SL4, 3RF4a, 3-5L2'),
        ('When My Thinking Changed', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL1 [3SL1d], 3-5L1'),
        ('The Feeling of Finally Understanding', 'Audio Postcard - NY Standards Alignment: 3SL4, 3RF4a, 3-5L2'),
        ('Making a Decision While Still Uncertain', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3-5L1'),
        ('Noticing How Someone Else Works Differently', 'Audio Postcard - NY Standards Alignment: 3SL1 [3SL1a], 3SL4, 3-5L1'),
        ('Slowing Down to Improve', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3-5L2'),
        ('When Difficulty Taught Me Something', 'Audio Postcard - NY Standards Alignment: 3SL4, 3-5L1, 3SL6'),
        ('What Kind of Learner I Am', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3-5L1'),
        ('When a New Strategy Worked', 'Audio Postcard - NY Standards Alignment: 3SL4, 3RF4a, 3-5L2'),
        ('Focused vs. Distracted — What I Notice', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3-5L1'),
        ('How I''ve Changed as a Learner', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3-5L1'),
        ('When Speaking Up Felt Difficult But Right', 'Audio Postcard - NY Standards Alignment: 3SL1 [3SL1a], 3SL4, 3-5L1'),
        ('What I Thought Was Impossible', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3-5L2'),
        ('Patterns in How I Handle New Challenges', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3-5L1'),
        ('What I Want to Carry Into Next Year', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3-5L2'),
        ('What Effort Means to Me', 'Audio Postcard - NY Standards Alignment: 3SL4, 3SL6, 3-5L1')
    ) AS v(lesson_name, new_desc)
),
m8_update_lesson AS (
    UPDATE bantrly.lesson l
    SET lesson_description = d.new_desc
    FROM m8_desc_data d
    WHERE l.lesson_name = d.lesson_name
      AND l.difficulty_level = 'HARD'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_id, l.lesson_name, d.new_desc
),
m8_update_version AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{lesson_description}',
            to_jsonb(ul.new_desc)
        )
    FROM m8_update_lesson ul
    WHERE lvn.lesson_id = ul.lesson_id
      AND lvn.is_latest = true
    RETURNING lvn.title
)

SELECT
    (SELECT COUNT(*) FROM m1_update_lesson) AS m1_lessons_updated,
    (SELECT COUNT(*) FROM m1_update_version)   AS m1_versions_updated,
    (SELECT COUNT(*) FROM m2_update_lesson) AS m2_lessons_updated,
    (SELECT COUNT(*) FROM m2_update_version)   AS m2_versions_updated,
    (SELECT COUNT(*) FROM m3_update_lesson) AS m3_lessons_updated,
    (SELECT COUNT(*) FROM m3_update_version)   AS m3_versions_updated,
    (SELECT COUNT(*) FROM m4_update_lesson) AS m4_lessons_updated,
    (SELECT COUNT(*) FROM m4_update_version)   AS m4_versions_updated,
    (SELECT COUNT(*) FROM m5_update_lesson) AS m5_lessons_updated,
    (SELECT COUNT(*) FROM m5_update_version)   AS m5_versions_updated,
    (SELECT COUNT(*) FROM m6_update_lesson) AS m6_lessons_updated,
    (SELECT COUNT(*) FROM m6_update_version)   AS m6_versions_updated,
    (SELECT COUNT(*) FROM m7_update_lesson) AS m7_lessons_updated,
    (SELECT COUNT(*) FROM m7_update_version)   AS m7_versions_updated,
    (SELECT COUNT(*) FROM m8_update_lesson) AS m8_lessons_updated,
    (SELECT COUNT(*) FROM m8_update_version)   AS m8_versions_updated;

COMMIT;
