-- Generated by generate_update_sql.py
-- Filters: difficulty=EASY | created_by=ee42009d-d83e-4c12-abd1-2d8fff809b18 | role=TEACHER
-- Fields updated: 1
-- Only the specified content_keys are changed; all other values remain untouched.

BEGIN;

WITH
-- M5 - Tongue Twisters: update 'tongue_twister' (30 lesson(s))
m5_tonguetwister_data AS (
    SELECT * FROM (VALUES
        ('Bright Bees Buzz', 'Bright bees buzz by blue blossoms.'),
        ('Tiny Turtles Turn', 'Tiny turtles turn toward tall trees.'),
        ('Silly Seals Slide', 'Silly seals slide on snowy slopes.'),
        ('Lovely Lions Lie', 'Lovely lions lie on long leaves.'),
        ('Fluffy Frogs Flip', 'Fluffy frogs flip and fly forward.'),
        ('Dandy Ducks Dive', 'Dandy ducks dive deep down.'),
        ('Giggling Geese Gather', 'Giggling geese gather golden grain in green grassy fields.'),
        ('Clever Cats Climb', 'Clever cats climb curvy cliffs to cross the creek.'),
        ('Merry Mice Move', 'Merry mice march through misty meadows at midday.'),
        ('Peaceful Puppies Play', 'Peaceful puppies play in pretty purple parks near the pond.'),
        ('Seven Snug Squirrels', 'Seven snug squirrels snuck snacks from the snow-covered shelf.'),
        ('Brave Bluebirds Bounce', 'Brave bluebirds boldly bounce between breezy branches at breakfast.'),
        ('Friendly Frogs Flip', 'Friendly frogs flip forward on fresh flat flowers near the stream.'),
        ('Tall Tulips Twist', 'Tall tulips twist toward the twinkly sky at twilight.'),
        ('Lucky Lanterns Light', 'Lucky lanterns lightly light the long, lonely lane in the sleepy village.'),
        ('Crispy Crackers Crunch', 'Crispy crackers crunch and crackle when cheerful children chew them by the creek.'),
        ('Shrieking Shrimp Shuffle', 'Shrieking shrimp shuffle sideways on the shiny shore at the edge of the shallow sea.'),
        ('Slippery Snakes Slither', 'Slippery snakes slither slowly through the slick, snowy slope near the sleeping village.'),
        ('Glowing Glowworms Glow', 'Glowing glowworms gleam and glisten along the gloomy, glassy riverbank at night.'),
        ('Three Thin Threads', 'Three thin threads threaded through the throat of a thrush sitting on a thorn.'),
        ('Sprinting Sprouts Spring', 'Sprinting sprouts spring up from the spread of soil after every splash of spring rain.'),
        ('Scrubbing Crabs Scrabble', 'Scrubbing crabs scrabble and scratch across the scratchy, crinkled creek bed in the cove.'),
        ('Twitching Twigs Twist', 'Twitching twigs twist and tremble in the strong, travelling breeze across the treetops.'),
        ('Splitting Splinters Splashed', 'Splitting splinters splashed and sprang from the strong, strange tree struck by the storm.'),
        ('Striking Streams Stream', 'Striking streams stream swiftly through the steep, straight stretch of the stony valley.'),
        ('Thrashing Thrushes Threw', 'Thrashing thrushes threw three thick chunks of chocolate through the thornbush near the bridge.'),
        ('Clinking Clocks Click', 'Clinking clocks click and creak as clever crows cling to the crown of the crumbling clock tower.'),
        ('Sparkling Sprats Sprang', 'Sparkling sprats sprang and splashed through the spreading spray at the edge of the splitting reef.'),
        ('Gripping Grizzlies Growl', 'Gripping grizzlies growl and groan as they graze across the great, grey, granite gravel slope.'),
        ('Scratchy Scrub Brushes Scrub', 'Scratchy scrub brushes bravely scrub and scrape the brown, brittle brick bridge in the brisk breeze.')
    ) AS v(lesson_name, new_value)
),
m5_tonguetwister_lc AS (
    UPDATE bantrly.lesson_content lc
    SET content_value = ud.new_value,
        updated_at = NOW()
    FROM bantrly.lesson l
    JOIN m5_tonguetwister_data ud ON ud.lesson_name = l.lesson_name
    WHERE lc.lesson_id = l.lesson_id
      AND lc.content_key = 'tongue_twister'
      AND l.difficulty_level = 'EASY'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_name
),
m5_tonguetwister_lv AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{contents,1,content_value}',
            to_jsonb(ud.new_value)
        )
    FROM bantrly.lesson l
    JOIN m5_tonguetwister_data ud ON ud.lesson_name = l.lesson_name
    WHERE lvn.lesson_id = l.lesson_id
      AND lvn.is_latest = true
      AND l.difficulty_level = 'EASY'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING lvn.title
)

SELECT
    (SELECT COUNT(*) FROM m5_tonguetwister_lc) AS m5_tonguetwister_content_updated,
    (SELECT COUNT(*) FROM m5_tonguetwister_lv) AS m5_tonguetwister_version_updated;

COMMIT;
