-- Generated by generate_update_sql.py
-- Filters: difficulty=EASY | created_by=ee42009d-d83e-4c12-abd1-2d8fff809b18 | role=TEACHER
-- Fields updated: 1
-- Only the specified content_keys are changed; all other values remain untouched.

BEGIN;

WITH
-- M6 - Poems: update 'assigned_text' (30 lesson(s))
m6_assignedtext_data AS (
    SELECT * FROM (VALUES
        ('Good Morning', 'The sun comes up, the day is new,
I stretch my arms and tie my shoe,
And head to school to learn something true.'),
        ('My Voice', 'My voice is mine — it''s small but strong,
I speak up clearly all day long,
And say my words where I belong.'),
        ('Listen Up', 'When someone speaks, I turn and hear,
I nod my head and lean in near,
Because their words are worth a hear.'),
        ('Keep on Trying', 'I miss a step but start again,
I try once more and wonder when
I''ll find the way — I will by ten.'),
        ('Reading Time', 'I open up my book and see
A story waiting just for me,
I read each word so carefully.'),
        ('Rain and Puddles', 'The raindrops fall on leaf and stone,
They splash and drip and splash alone,
Then dry away — the puddle''s gone.'),
        ('Brave Enough', 'It scares me some to stand up tall,
But brave is not about no fear at all —
It''s taking one more step before I fall.'),
        ('The Quiet Moment', 'Sometimes the world moves fast and loud,
So I close my eyes behind the crowd,
And breathe until my mind''s not loud.'),
        ('A Good Friend', 'A friend who listens, stands, and stays
Is worth a million sunny days —
I try to be that friend always.'),
        ('Classroom Voices', 'Inside we use a gentle sound,
Our voices soft and safely wound —
The right voice for the space we''ve found.'),
        ('Make a Mistake', 'I made a wrong — I said so clear,
I tried again without the fear,
And got it right on my next year.'),
        ('Sharing Space', 'This desk is yours, and this is mine,
But when we share, it turns out fine —
Two minds together build the line.'),
        ('The Stars at Night', 'The stars come out when school is done,
They flicker where the moon has spun —
A sky that never outgrows fun.'),
        ('Helping Hands', 'My hands can hold, my hands can share,
They reach for those who need some care —
Helping hands are everywhere.'),
        ('Words Matter', 'The words I say can lift or break,
So I choose them for kindness'' sake —
Words matter in the moves I make.'),
        ('What Curiosity Feels Like', 'A question is a door flung wide,
That pulls the whole world back inside —
Curiosity is my best guide.'),
        ('Growing Up Slowly', 'I''m not who I was yesterday,
And not yet who I''ll be someday —
Growing means I''m on the way.'),
        ('The Last Try', 'I wanted to quit — I nearly did,
But deep inside me something hid
The try that finally flipped the lid.'),
        ('Inside the Story', 'The page turns quiet, and I''m in —
The world around me grows thin skin —
The story living beneath my chin.'),
        ('What Fairness Looks Like', 'Fair doesn''t mean we all get same —
It means each player plays the game
With what they need to reach the frame.'),
        ('Paying Attention', 'The world is full of things to miss
When minds move fast and eyes go whiz —
Slowing down is where the real thing is.'),
        ('Who I''m Becoming', 'I don''t know all of who I''ll be,
But every choice is shaping me —
The self I''m growing, step by step, is free.'),
        ('The Sound of Learning', 'A classroom hums with thinking minds,
The kind of sound a question finds —
Every answer new unwinds.'),
        ('Roots and Wings', 'Roots hold me where my story grew,
But wings are what I''m reaching to —
Between the two, I''m something new.'),
        ('The Shape of a Question', 'A question has no finished side —
It opens outward, deep and wide,
And pulls the whole truth back inside.'),
        ('What Silence Teaches', 'Silence isn''t empty air —
It holds the thoughts that need more care,
And clears the space for what is rare.'),
        ('Both Things True', 'Two things can be true at once, I find —
I''m scared and brave inside my mind,
The in-between is my own kind.'),
        ('The Long Way Around', 'The longest road is sometimes right,
It leads through shadow into light —
The short way skips what makes you bright.'),
        ('What We Leave Behind', 'What will remain when I have gone?
The kindness carried, passed along —
The echo of a voice still strong.'),
        ('Making Meaning', 'Meaning isn''t handed down —
I search the sounds and words I''ve found,
And build it from the ground around.')
    ) AS v(lesson_name, new_value)
),
m6_assignedtext_lc AS (
    UPDATE bantrly.lesson_content lc
    SET content_value = ud.new_value,
        updated_at = NOW()
    FROM bantrly.lesson l
    JOIN m6_assignedtext_data ud ON ud.lesson_name = l.lesson_name
    WHERE lc.lesson_id = l.lesson_id
      AND lc.content_key = 'assigned_text'
      AND l.difficulty_level = 'EASY'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_name
),
m6_assignedtext_lv AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{contents,1,content_value}',
            to_jsonb(ud.new_value)
        )
    FROM bantrly.lesson l
    JOIN m6_assignedtext_data ud ON ud.lesson_name = l.lesson_name
    WHERE lvn.lesson_id = l.lesson_id
      AND lvn.is_latest = true
      AND l.difficulty_level = 'EASY'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING lvn.title
)

SELECT
    (SELECT COUNT(*) FROM m6_assignedtext_lc) AS m6_assignedtext_content_updated,
    (SELECT COUNT(*) FROM m6_assignedtext_lv) AS m6_assignedtext_version_updated;

COMMIT;
