-- Generated by generate_update_sql.py
-- Filters: difficulty=HARD | created_by=ee42009d-d83e-4c12-abd1-2d8fff809b18 | role=TEACHER
-- Fields updated: 1
-- Only the specified content_keys are changed; all other values remain untouched.

BEGIN;

WITH
-- M5 - Tongue Twisters: update 'tongue_twister' (30 lesson(s))
m5_tonguetwister_data AS (
    SELECT * FROM (VALUES
        ('Striped Storks Stride', 'Striped storks stride swiftly through steep stone steps.'),
        ('Shiny Shells Shift', 'Shiny shells shift slowly on shallow shoreline stones.'),
        ('Three Thrushes Thrash', 'Three thrushes thrash through thorny thickets twice daily.'),
        ('Spiral Springs Spread', 'Spiral springs spread sprouts across springtime stone streams.'),
        ('Clever Crows Clutch', 'Clever crows clutch crisp crackling crumbs near creeks.'),
        ('Splotchy Snails Slip', 'Splotchy snails slip past splintered stumps in shadows.'),
        ('Striped Skinks Skip', 'Striped skinks skip and skitter across slick stone slopes.'),
        ('Twisted Twigs Twirl', 'Twisted twigs twirl through treetops in the twilight wind.'),
        ('Shrewd Shrews Shred', 'Shrewd shrews shred shimmering shrubs near the shallow stream.'),
        ('Flipped Freckled Frogs', 'Freckled frogs frantically flip from slippery flat flagstones.'),
        ('Whistling Winds Whirl', 'Whistling winds whirl and whip through wide wet wheatfields.'),
        ('Crackling Creek Crabs', 'Crackling creek crabs crawl carefully across crumbling clay cliffs.'),
        ('Spotted Starlings Swoop', 'Spotted starlings swoop swiftly between swaying steel spire tips.'),
        ('Stealthy Scorpions Scuttle', 'Stealthy scorpions scuttle and scatter across slick scattered gravel.'),
        ('Screaming Swallows Sweep', 'Screaming swallows sweep and swoop past splintered shipwreck planks.'),
        ('Stitched Scarves Strewn', 'Skillfully stitched scarves strewn across twelve swirling stone staircases.'),
        ('Thrilling Thresholds Thrust', 'Thrilling threadbare thresholds thrust through three thick thornbush tangles.'),
        ('Sprightly Squirrels Sprint', 'Sprightly squirrels sprint past sprawling spruce and spindly sprout stalks.'),
        ('Slippery Snowflakes Spiral', 'Slippery snowflakes spiral softly settling across steep slanted stone structures.'),
        ('Swift Starlings Skim', 'Strikingly swift starlings skim and streak past swirling storm cloud banks.'),
        ('Scrunching Spring Sprockets', 'Scrunching spring sprockets sprang apart and scattered across slick wet slate.'),
        ('Swishing Swans Swept', 'Swishing swans swept swiftly past splashing sprinkling springtime sparkling shores.'),
        ('Stretching Sprouts Strain', 'Stretching stiff-stalked sprouts strain steadily upward toward shimmering silver skies.'),
        ('Strangely Twisted Thornbushes', 'Strangely twisted thornbushes thrust through twelve shrieking shrubs near shimmering streams.'),
        ('Crinkled Crustaceans Crawled', 'Crinkled crackling crustaceans crawled and crashed across crumbling crystalline cliff faces.'),
        ('Sprawling Speckled Sparrows', 'Sprawling speckled sparrows sweep past spinning splintered steeple spire tips above.'),
        ('Shriveled Shrunken Shrubs', 'Shriveled shrunken shrubs shudder sharply through shrieking thunderstruck showers and shards.'),
        ('Swiftly Switching Streaks', 'Swiftly switching streaks of pale starlight skim across steep silvery sky slopes.'),
        ('Sprinkling Sprinklers Sprayed', 'Sprinkling sprinklers sprayed sparkling sprouts across spreading springtime structured stone stretches.'),
        ('Stretching Straining Storks', 'Stretching, straining, strikingly strong storks strode through streams of streaming silver starlight.')
    ) AS v(lesson_name, new_value)
),
m5_tonguetwister_lc AS (
    UPDATE bantrly.lesson_content lc
    SET content_value = ud.new_value,
        updated_at = NOW()
    FROM bantrly.lesson l
    JOIN m5_tonguetwister_data ud ON ud.lesson_name = l.lesson_name
    WHERE lc.lesson_id = l.lesson_id
      AND lc.content_key = 'tongue_twister'
      AND l.difficulty_level = 'HARD'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_name
),
m5_tonguetwister_lv AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{contents,1,content_value}',
            to_jsonb(ud.new_value)
        )
    FROM bantrly.lesson l
    JOIN m5_tonguetwister_data ud ON ud.lesson_name = l.lesson_name
    WHERE lvn.lesson_id = l.lesson_id
      AND lvn.is_latest = true
      AND l.difficulty_level = 'HARD'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING lvn.title
)

SELECT
    (SELECT COUNT(*) FROM m5_tonguetwister_lc) AS m5_tonguetwister_content_updated,
    (SELECT COUNT(*) FROM m5_tonguetwister_lv) AS m5_tonguetwister_version_updated;

COMMIT;
