-- Generated by generate_update_sql.py
-- Filters: difficulty=HARD | created_by=ee42009d-d83e-4c12-abd1-2d8fff809b18 | role=TEACHER
-- Fields updated: 1
-- Only the specified content_keys are changed; all other values remain untouched.

BEGIN;

WITH
-- M6 - Poems: update 'assigned_text' (30 lesson(s))
m6_assignedtext_data AS (
    SELECT * FROM (VALUES
        ('Listening', 'When I stop my own voice for a moment and wait,
I hear what was already there, steady and straight.
Listening is how I find what I nearly missed.'),
        ('Changing Your Mind', 'Yesterday''s answer felt certain and true,
but new information rearranged the view.
Changing your mind is a kind of strength too.'),
        ('Asking Why', 'The question sits quietly, waiting to grow,
pressing against what I already know.
Asking "why" is the first step of flow.'),
        ('Making Mistakes', 'A mistake is a message sent from the path,
it says: try again, recalculate the math.
Learning begins in the long aftermath.'),
        ('Trying Again', 'The attempt that failed left a small kind of mark,
not a scar, but a map through the difficult dark.
Trying again is the point, not just the start.'),
        ('Patience', 'Patience does not mean nothing is happening here,
it means something is forming, layer by layer.
Wait, and what matters will suddenly appear.'),
        ('Noticing Others', 'Their face held something before any word was said,
a shift, a stillness, a quiet thread.
I noticed it, and something changed instead.'),
        ('When Words Are Hard to Find', 'The feeling arrived before language could form,
a shape without name, somewhere between calm and storm.
I waited, and slowly, the words settled warm.'),
        ('The Space Before Speaking', 'Between what I think and the moment I say,
there''s a small quiet place I can choose to stay.
The right words wait there, already on their way.'),
        ('Being Brave Without Knowing It', 'I didn''t feel brave when I stood up to speak,
just quietly nervous in the middle of the week.
But brave is the word others said, cheek to cheek.'),
        ('Losing and Learning', 'Losing doesn''t always mean I got it wrong,
sometimes it means the lesson had to come along.
What stays with me after is stronger than the song.'),
        ('What Fairness Feels Like', 'Fairness isn''t always the same for each seat,
it means everyone gets what they need to complete.
The table must fit every person who meets.'),
        ('When Quiet Is Loud', 'A room that says nothing can still carry weight,
the absence of words can say something quite great.
Silence, I''ve learned, can communicate.'),
        ('Deciding Alone', 'No one was there to say what was right,
just me and the choice at the edge of the night.
I made it, and carried it into the light.'),
        ('The Weight of Kindness', 'Kindness is lighter than anger to hold,
but it travels farther through the cold.
One act repeated becomes something bold.'),
        ('The Shape of Courage', 'Courage isn''t loud, it doesn''t shout or blaze,
it moves in small steps through uncertain haze.
Its shape reveals itself inside the maze.'),
        ('When Something New Feels Wrong', 'Unfamiliar things press against what I know,
like weather arriving in places I don''t go.
But wrong and new are not always the same, though.'),
        ('Choosing Carefully', 'Every choice removes a different door,
the one I take becomes the floor.
I walk it forward, learning more and more.'),
        ('Want Versus Need', 'Want is a flag that flies bright and loud,
need is the root beneath the ground.
I''ve learned to tell one from the other sound.'),
        ('Finding Your Pace', 'I used to match my speed to all the rest,
but slower thinking sometimes does it best.
My pace, I found, is how I take the test.'),
        ('What Persistence Looks Like', 'It doesn''t look like triumph every day,
most times it''s just returning, come what may.
Persistence is the act of choosing to stay.'),
        ('When Understanding Arrives', 'The idea arrived like light through a narrow crack,
not all at once, but slowly tracking back.
Understanding came, and nothing pushed it back.'),
        ('Growing Without Noticing', 'I didn''t feel myself becoming more,
but one day I could open a different door,
one I''d found too heavy long before.'),
        ('What Thinking Is Made Of', 'Thinking is not a straight road to the end,
it circles back and doubles round the bend,
a process, not a product, I defend.'),
        ('The Voice You Choose', 'Every speaker selects from what they carry,
some voices are certain, some careful, some wary.
The voice that I choose becomes my dictionary.'),
        ('When Silence Speaks', 'Some truths arrive without a single word,
their presence is felt before they are heard.
Silence, used well, is the sharpest third.'),
        ('Learning as a Map', 'A map is not the territory, just a guide,
and learning is the same, a rough outside.
The landscape shifts when you are deep inside.'),
        ('What You Carry Forward', 'Not every lesson can be taught or told,
some are discovered in the doing, then hold.
What you carry forward is your own to mold.'),
        ('The Edge of What You Know', 'At the edge of what I know, the ground gets thin,
and that is where the real learning can begin.
I step out carefully, taking everything in.'),
        ('Beginning Again', 'Starting over doesn''t erase what was built,
it lifts the weight of accumulated silt.
Beginning again is not a reason for guilt.')
    ) AS v(lesson_name, new_value)
),
m6_assignedtext_lc AS (
    UPDATE bantrly.lesson_content lc
    SET content_value = ud.new_value,
        updated_at = NOW()
    FROM bantrly.lesson l
    JOIN m6_assignedtext_data ud ON ud.lesson_name = l.lesson_name
    WHERE lc.lesson_id = l.lesson_id
      AND lc.content_key = 'assigned_text'
      AND l.difficulty_level = 'HARD'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_name
),
m6_assignedtext_lv AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{contents,1,content_value}',
            to_jsonb(ud.new_value)
        )
    FROM bantrly.lesson l
    JOIN m6_assignedtext_data ud ON ud.lesson_name = l.lesson_name
    WHERE lvn.lesson_id = l.lesson_id
      AND lvn.is_latest = true
      AND l.difficulty_level = 'HARD'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING lvn.title
)

SELECT
    (SELECT COUNT(*) FROM m6_assignedtext_lc) AS m6_assignedtext_content_updated,
    (SELECT COUNT(*) FROM m6_assignedtext_lv) AS m6_assignedtext_version_updated;

COMMIT;
