-- Generated by generate_update_sql.py
-- Filters: difficulty=MEDIUM | created_by=ee42009d-d83e-4c12-abd1-2d8fff809b18 | role=TEACHER
-- Fields updated: 1
-- Only the specified content_keys are changed; all other values remain untouched.

BEGIN;

WITH
-- M5 - Tongue Twisters: update 'tongue_twister' (30 lesson(s))
m5_tonguetwister_data AS (
    SELECT * FROM (VALUES
        ('Wiggly Worms Weave Webs', 'Wiggly worms weave webs in willows.'),
        ('Golden Geese Glide', 'Golden geese glide down green gorges.'),
        ('Rushing Rabbits Race', 'Rushing rabbits race around rocky roads.'),
        ('Dizzy Dolphins Dash', 'Dizzy dolphins dash through dark dunes.'),
        ('Muddy Moose Munch Mushrooms', 'Muddy moose munch many crunchy mushrooms.'),
        ('Shiny Shells Shine', 'Shiny shells shine sharply on shores.'),
        ('Six Slippery Snails', 'Six slippery snails slid slowly southward.'),
        ('Three Thick Thorny Thistles', 'Three thick thorny thistles thump together.'),
        ('Plump Purple Plums', 'Plump purple plums pile past ponds.'),
        ('Crunchy Crickets Creep', 'Crunchy crickets creep across crinkled creeks.'),
        ('Bright Bronze Beetles', 'Bright bronze beetles buzz beside bark.'),
        ('Twisting Twigs Tangle', 'Twisting twigs tangle between tall trunks.'),
        ('Freckled Frogs Flip', 'Freckled frogs flip flat feet forward.'),
        ('Greedy Gray Geese', 'Greedy gray geese grab green grains.'),
        ('Clapping Clams Clatter', 'Clapping clams clatter close by cliffs.'),
        ('Grumpy Groundhogs Groan', 'Grumpy groundhogs groan gathering gray grains.'),
        ('Creaky Cranes Carry Cargo', 'Creaky cranes carry cargo carefully crosswise.'),
        ('Slender Swallows Swoop', 'Slender swallows swoop through swift storms.'),
        ('Wobbly Wolves Wade', 'Wobbly wolves wade past wide whirlpools.'),
        ('Striped Starfish Stretch', 'Striped starfish stretch stiff spiny arms.'),
        ('Brown Bluebirds Brush Blossoms', 'Brown bluebirds brush blossoms beside branches.'),
        ('Sneaky Snakes Slither', 'Sneaky snakes slither sideways through streams.'),
        ('Prancing Ponies Prance', 'Prancing ponies prance past pretty pastures.'),
        ('Scruffy Squirrels Scramble', 'Scruffy squirrels scurry scrambling through scrub.'),
        ('Stiff Straight Strands Stretch', 'Stiff straight strands stretch across still streams.'),
        ('Thirty Thick Threads', 'Thirty thick threads threaded through thin thickets.'),
        ('Flickering Fireflies Flit', 'Flickering fireflies flit freely from flowers.'),
        ('Spotted Sparrows Spring', 'Spotted sparrows spring past splintered sprouts.'),
        ('Glittering Glaciers Glow', 'Glittering glaciers glow giving grand glimpses.'),
        ('Skillful Skunks Sketch Shapes', 'Skillful skunks sketch scratchy scaly shapes.')
    ) AS v(lesson_name, new_value)
),
m5_tonguetwister_lc AS (
    UPDATE bantrly.lesson_content lc
    SET content_value = ud.new_value,
        updated_at = NOW()
    FROM bantrly.lesson l
    JOIN m5_tonguetwister_data ud ON ud.lesson_name = l.lesson_name
    WHERE lc.lesson_id = l.lesson_id
      AND lc.content_key = 'tongue_twister'
      AND l.difficulty_level = 'MEDIUM'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_name
),
m5_tonguetwister_lv AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{contents,1,content_value}',
            to_jsonb(ud.new_value)
        )
    FROM bantrly.lesson l
    JOIN m5_tonguetwister_data ud ON ud.lesson_name = l.lesson_name
    WHERE lvn.lesson_id = l.lesson_id
      AND lvn.is_latest = true
      AND l.difficulty_level = 'MEDIUM'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING lvn.title
)

SELECT
    (SELECT COUNT(*) FROM m5_tonguetwister_lc) AS m5_tonguetwister_content_updated,
    (SELECT COUNT(*) FROM m5_tonguetwister_lv) AS m5_tonguetwister_version_updated;

COMMIT;
