-- Generated by generate_update_sql.py
-- Filters: difficulty=MEDIUM | created_by=ee42009d-d83e-4c12-abd1-2d8fff809b18 | role=TEACHER
-- Fields updated: 1
-- Only the specified content_keys are changed; all other values remain untouched.

BEGIN;

WITH
-- M6 - Poems: update 'assigned_text' (30 lesson(s))
m6_assignedtext_data AS (
    SELECT * FROM (VALUES
        ('The First Try', 'The blank page waits — I pick up my pen,
the first word is hardest, but once it begins,
the rest of the story rushes in.'),
        ('After the Rain', 'The storm blew through and bent every tree,
but after the rain the air smelled clean and free,
and a rainbow curved just for me to see.'),
        ('My Best Friend', 'You know when I''m quiet that something''s not right,
you sit close beside me and don''t ask why,
some friendships don''t need a single reply.'),
        ('Morning Light', 'The window glows gold before school begins,
I pack what I need and breathe the cool air in,
today is a page I haven''t written yet.'),
        ('The Mistake', 'I said the wrong thing and felt my face go red,
but I went back and changed what I''d said,
fixing a mistake means the weight lifts from your head.'),
        ('Autumn Leaves', 'Red and gold, they let go of the branch,
not because they''re lost, but because it''s their chance —
even falling can look like a dance.'),
        ('Two Feelings', 'I''m nervous and excited — they feel the same,
my heart beats fast before I hear my name,
and brave is just scared with a different frame.'),
        ('The Book I Couldn''t Close', 'Long past bedtime, one more page,
the story pulled me into its world like a cage,
I didn''t want to leave — I was living on its stage.'),
        ('Practicing', 'The first ten tries sound nothing like the last,
between the clumsy start and the fast
is the quiet middle where learning gets amassed.'),
        ('Winter Morning', 'The ground wore white before the sun arrived,
each footprint pressed a path through frozen grass,
and breath came out in clouds that didn''t last.'),
        ('The Hard Question', 'I raised my hand even though I wasn''t sure,
the question sat inside me like a closed door,
and asking it cracked the room open more.'),
        ('Listening', 'I used to wait for my turn to speak,
now I listen all the way to the deep,
and find the things I used to miss asleep.'),
        ('The New Student', 'She stood at the door with nowhere to go,
I moved my bag over — she sat in the row,
now she''s the best part of science, I know.'),
        ('Spring Arrives', 'The mud smells alive after months of cold,
the first green shoots push through soil and hold,
spring doesn''t ask permission — it''s bold.'),
        ('Reading Together', 'When we read aloud, the words belong to all,
my voice carries further in that hall,
together we hold the story — we don''t let it fall.'),
        ('The Long Way Around', 'The shortcut was faster — I took the long trail,
I missed where I was going but found the detail,
sometimes the slow road is the one that doesn''t fail.'),
        ('What I Keep', 'I forget most Tuesdays — but I keep the smell
of rain on hot pavement and the dinner bell,
some things stay forever without anyone to tell.'),
        ('Growing Slowly', 'I''m not the same as I was last spring,
but the change came so quiet I didn''t feel a thing —
growing is slow like seeds, not sudden like a ring.'),
        ('The Storm That Passed', 'The fight was loud and left a quiet behind,
the kind of quiet that''s harder to find,
but the air after storms is the clearing kind.'),
        ('What I Notice', 'Most people passed the spider''s web today,
I stopped to watch the morning light at play —
slowing down is a kind of seeing anyway.'),
        ('The Question Behind the Question', 'I asked why the sky was blue and you said light,
but I meant why the world holds itself so right,
some questions open wider the more you hold them tight.'),
        ('Different and the Same', 'We eat different things and speak different ways,
but we all put hands up on uncertain days,
and we all go quiet when the last light fades.'),
        ('What the Tree Knows', 'The oak doesn''t hurry to reach the sky —
it holds its ground while the seasons go by,
some things grow strongest when they don''t try.'),
        ('Roots and Wings', 'My roots hold where my story first grew,
but my wings keep reaching somewhere new —
I carry both, and they carry me through.'),
        ('Both at Once', 'I can miss the old thing and love the new,
I can be scared and still push through —
being two things at once is what growing does to you.'),
        ('Silence Before Speaking', 'The best thing I said this week I almost didn''t say,
I held it back, let it settle, then found the right way —
silence before speaking is not the same as having nothing to say.'),
        ('Small and Important', 'No one will write about the cup I returned,
the door I held, the patience I learned,
but quiet things matter even when they go unearned.'),
        ('Reading the Room', 'Before I spoke, I looked around the table first —
his eyes were down, her shoulders braced for the worst,
I chose my words like water — not like a burst.'),
        ('The Echo', 'What I say in the morning follows me all day,
like an echo that shapes itself along the way —
I try to send out the kind I want to stay.'),
        ('What I''m Still Learning', 'I don''t know yet who I''ll grow up to be,
but I know each day adds a ring to the tree —
still learning is its own kind of mastery.')
    ) AS v(lesson_name, new_value)
),
m6_assignedtext_lc AS (
    UPDATE bantrly.lesson_content lc
    SET content_value = ud.new_value,
        updated_at = NOW()
    FROM bantrly.lesson l
    JOIN m6_assignedtext_data ud ON ud.lesson_name = l.lesson_name
    WHERE lc.lesson_id = l.lesson_id
      AND lc.content_key = 'assigned_text'
      AND l.difficulty_level = 'MEDIUM'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_name
),
m6_assignedtext_lv AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{contents,1,content_value}',
            to_jsonb(ud.new_value)
        )
    FROM bantrly.lesson l
    JOIN m6_assignedtext_data ud ON ud.lesson_name = l.lesson_name
    WHERE lvn.lesson_id = l.lesson_id
      AND lvn.is_latest = true
      AND l.difficulty_level = 'MEDIUM'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING lvn.title
)

SELECT
    (SELECT COUNT(*) FROM m6_assignedtext_lc) AS m6_assignedtext_content_updated,
    (SELECT COUNT(*) FROM m6_assignedtext_lv) AS m6_assignedtext_version_updated;

COMMIT;
