-- Generated by generate_update_sql.py
-- Filters: difficulty=MEDIUM | created_by=ee42009d-d83e-4c12-abd1-2d8fff809b18 | role=TEACHER
-- Fields updated: 1
-- Only the specified content_keys are changed; all other values remain untouched.

BEGIN;

WITH
-- M1 - Reading Paragraph: update 'example' (30 lesson(s))
m1_example_data AS (
    SELECT * FROM (VALUES
        ('A New Seat', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('The Missing Pencil', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('Too Loud', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('Sharing the Crayons', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('A Rainy Day', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('First Day Jitters', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('The Fair Turn', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('Speaking Up', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('When Friends Disagree', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('The Group Project', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('Left Out at Lunch', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('Keeping a Promise', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('The Too-Fast Game', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('Different Ways to Learn', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('A Mistake in Class', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('Making Things Right', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('The New Student', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('When It''s Hard to Focus', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('Two Friends, One Ball', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('The Big Test Worry', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('Noticing When Someone Is Sad', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('Changing the Plan', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('Standing Up for a Friend', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('A Pattern I Noticed in Myself', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('Saying No Kindly', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('When the Rules Don''t Seem Fair', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('Taking Care of Someone Else''s Feelings', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('A Long Wait', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('Changing How I Think About Mistakes', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.'),
        ('The Group Decides Together', 'Jamal forgot his lunch and felt embarrassed. He sat quietly at his desk, hoping no one would notice. His friend Priya saw him and offered to share her sandwich. They ate together and talked about their morning. Jamal smiled and said thank you. After class, he drew a small thank-you note for her. By the end of the day, he felt cared for. He learned that a small act of kindness can turn a hard day around.')
    ) AS v(lesson_name, new_value)
),
m1_example_lc AS (
    UPDATE bantrly.lesson_content lc
    SET content_value = ud.new_value,
        updated_at = NOW()
    FROM bantrly.lesson l
    JOIN m1_example_data ud ON ud.lesson_name = l.lesson_name
    WHERE lc.lesson_id = l.lesson_id
      AND lc.content_key = 'example'
      AND l.difficulty_level = 'MEDIUM'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING l.lesson_name
),
m1_example_lv AS (
    UPDATE bantrly.lesson_version_new lvn
    SET content = jsonb_set(
            lvn.content::jsonb,
            '{contents,1,content_value}',
            to_jsonb(ud.new_value)
        )
    FROM bantrly.lesson l
    JOIN m1_example_data ud ON ud.lesson_name = l.lesson_name
    WHERE lvn.lesson_id = l.lesson_id
      AND lvn.is_latest = true
      AND l.difficulty_level = 'MEDIUM'
      AND l.created_by = 'ee42009d-d83e-4c12-abd1-2d8fff809b18'
      AND l.created_by_role = 'TEACHER'
    RETURNING lvn.title
)

SELECT
    (SELECT COUNT(*) FROM m1_example_lc) AS m1_example_content_updated,
    (SELECT COUNT(*) FROM m1_example_lv) AS m1_example_version_updated;

COMMIT;
